CONTRIBUTING.md, README.md, build.gradle, src/main/java/io/openliberty/tools/intellij/LibertyExplorer.java, src/main/resources/META-INF/plugin.xml
- update documentation for IntelliJ Marketplace
- minor adjustment to `Liberty Explorer` to only display tree view if valid config files are found in the project
=> updated documentation

src/main/java/io/openliberty/tools/intellij/LibertyExplorer.java, src/main/java/io/openliberty/tools/intellij/actions/ExecuteLibertyDevTask.java, src/main/java/io/openliberty/tools/intellij/actions/LibertyToolbarActionGroup.java, src/main/java/io/openliberty/tools/intellij/actions/RefreshLibertyToolbar.java, src/main/java/io/openliberty/tools/intellij/util/Constants.java, src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java, src/main/java/io/openliberty/tools/intellij/util/TreeDataProvider.java, src/main/resources/META-INF/plugin.xml
- Updated vendor name to `Open-Liberty` in `plugin.xml`
- Fix in [getTerminalWidget](https://github.com/OpenLiberty/open-liberty-tools-intellij/compare/master...kathrynkodama:dev?expand=1#diff-48f1ecd020366bdb7adaa61fefdd87b1R64) to address Linux issue where the Linux machine could not connect to the terminal
- Modified the order of the `Execute Liberty Dev Task` so that user is prompted to select a project first and then a task to execute.  Tasks available to select are now filtered on project type
- Fix for the collapse/expand all buttons in the dashboard.  Previously if users hit the refresh button the collapse and expand all buttons stopped working.  Now they are linked to the updated Tree object.
=> Terminal issue fix, collapse/expand fix, execute task fix

README.md, src/main/java/io/openliberty/tools/intellij/actions/LibertyToolbarActionGroup.java, src/main/java/io/openliberty/tools/intellij/actions/RunLibertyDevTask.java, src/main/resources/META-INF/plugin.xml
=> Changed "Execute Liberty Dev Task" to "Run LIberty Dev Task"

src/main/java/io/openliberty/tools/intellij/actions/RunLibertyDevTask.java
=> default to projectName if cannot resolve root node

README.md, src/main/resources/META-INF/plugin.xml
=> update badges and IntelliJ version

src/main/resources/META-INF/plugin.xml
=> removed until-build

src/main/resources/META-INF/plugin.xml
Fixes #31 
Update description to include keywords: cloud-native, Jakarta EE, microservices, MicroProfile, etc.
=> update description of plugin

README.md
=> Add downloads badge to readme

build.gradle, src/main/java/io/openliberty/tools/intellij/actions/RunLibertyDevTask.java, src/main/java/io/openliberty/tools/intellij/util/Constants.java, src/main/resources/META-INF/plugin.xml
=> Rename tool window and run action disabled when selection is invalid

src/main/java/io/openliberty/tools/intellij/actions/LibertyDevCustomStartAction.java, src/main/java/io/openliberty/tools/intellij/actions/LibertyDevRunTestsAction.java, src/main/java/io/openliberty/tools/intellij/actions/LibertyDevStartAction.java, src/main/java/io/openliberty/tools/intellij/actions/LibertyDevStartContainerAction.java, src/main/java/io/openliberty/tools/intellij/actions/LibertyDevStopAction.java, src/main/java/io/openliberty/tools/intellij/actions/LibertyGeneralAction.java, src/main/java/io/openliberty/tools/intellij/actions/ViewEffectivePom.java, src/main/java/io/openliberty/tools/intellij/actions/ViewGradleConfig.java, src/main/java/io/openliberty/tools/intellij/actions/ViewIntegrationTestReport.java, src/main/java/io/openliberty/tools/intellij/actions/ViewTestReport.java, src/main/java/io/openliberty/tools/intellij/actions/ViewUnitTestReport.java, src/main/java/io/openliberty/tools/intellij/util/Constants.java, src/main/resources/META-INF/plugin.xml
Partial fix for #42 
Updated wording for the actions defined in the "Liberty" tool window
Updated titles for actions to include "Liberty" when searching workspace for actions
Refactored common tasks for actions into the "LibertyGeneralAction" class.
=> Refactor actions and update names

build.gradle
=> Increment version to 0.0.6

docs/LanguageServerIntegration.md, src/main/java/com/langserver/devtools/intellij/liberty/lsp/BoostrapPropertiesFileType.java, src/main/java/com/langserver/devtools/intellij/liberty/lsp/BoostrapPropertiesLanguage.java, src/main/java/com/langserver/devtools/intellij/liberty/lsp/BootstrapPropertiesFileType.java, src/main/java/com/langserver/devtools/intellij/liberty/lsp/BootstrapPropertiesLanguage.java, src/main/java/com/langserver/devtools/intellij/liberty/lsp/LibertyLanguageClient.java, src/main/java/com/langserver/devtools/intellij/liberty/lsp/LibertyLanguageServer.java, src/main/java/com/langserver/devtools/intellij/liberty/lsp/LibertyXmlServer.java, src/main/java/com/langserver/devtools/intellij/liberty/lsp/ServerEnvFileType.java, src/main/java/com/langserver/devtools/intellij/liberty/lsp/ServerEnvLanguage.java, src/main/java/com/langserver/devtools/intellij/lsp4mp/lsp/MicroProfileConfigFileType.java, src/main/java/com/langserver/devtools/intellij/lsp4mp/lsp/MicroProfileConfigLanguage.java, src/main/java/com/langserver/devtools/intellij/lsp4mp/lsp4ij/operations/completion/LSContentAssistProcessor.java, src/main/resources/META-INF/lsp.xml
Fixes #68 
Opened #91 to address https://github.com/OpenLiberty/liberty-tools-intellij/pull/90/files#diff-12df3a347e62e7521e290c35c86dbab57754060c72fd3737164501e7bb779b18R43-R45
=> Consume liberty-ls for bootstrap.properties and server.env files

.run/open-liberty-tools-intellij [runIde].run.xml
=> Check-in run/debug config

README.md, src/main/java/io/openliberty/tools/intellij/LibertyActionNode.java, src/main/java/io/openliberty/tools/intellij/LibertyDevToolWindowFactory.java, src/main/java/io/openliberty/tools/intellij/LibertyExplorer.java, src/main/java/io/openliberty/tools/intellij/LibertyPluginIcons.java, src/main/java/io/openliberty/tools/intellij/LibertyProjectNode.java, src/main/java/io/openliberty/tools/intellij/actions/LibertyDevCustomStartAction.java, src/main/java/io/openliberty/tools/intellij/actions/LibertyDevRunTestsAction.java, src/main/java/io/openliberty/tools/intellij/actions/LibertyDevStartAction.java, src/main/java/io/openliberty/tools/intellij/actions/LibertyDevStartContainerAction.java, src/main/java/io/openliberty/tools/intellij/actions/LibertyDevStopAction.java, src/main/java/io/openliberty/tools/intellij/actions/LibertyGeneralAction.java, src/main/java/io/openliberty/tools/intellij/actions/LibertyToolbarActionGroup.java, src/main/java/io/openliberty/tools/intellij/actions/RefreshLibertyToolbar.java, src/main/java/io/openliberty/tools/intellij/actions/RunLibertyDevTask.java, src/main/java/io/openliberty/tools/intellij/actions/ViewEffectivePom.java, src/main/java/io/openliberty/tools/intellij/actions/ViewGradleConfig.java, src/main/java/io/openliberty/tools/intellij/actions/ViewIntegrationTestReport.java, src/main/java/io/openliberty/tools/intellij/actions/ViewTestReport.java, src/main/java/io/openliberty/tools/intellij/actions/ViewUnitTestReport.java, src/main/java/io/openliberty/tools/intellij/util/BuildFile.java, src/main/java/io/openliberty/tools/intellij/util/Constants.java, src/main/java/io/openliberty/tools/intellij/util/LibertyActionUtil.java, src/main/java/io/openliberty/tools/intellij/util/LibertyGradleUtil.java, src/main/java/io/openliberty/tools/intellij/util/LibertyMavenUtil.java, src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java, src/main/java/io/openliberty/tools/intellij/util/LocalizedResourceUtil.java, src/main/java/io/openliberty/tools/intellij/util/TreeDataProvider.java, src/main/resources/META-INF/plugin.xml, src/main/resources/messages/LibertyBundles.properties
=> i18n localization, externalize user displayed messages to properties file

src/main/java/com/langserver/devtools/intellij/lsp4mp/lsp4ij/operations/diagnostics/LSPDiagnosticsToMarkers.java, src/main/java/com/langserver/devtools/intellij/lsp4mp/lsp4ij/operations/diagnostics/LSPLocalInspectionTool.java
=> If DiagnosticSeverity is not set, default to Error

build.gradle, src/main/java/com/langserver/devtools/intellij/liberty/lsp/LibertyLanguageClient.java
Update LemMinX version to work with the latest on the main branch of the liberty language server 
=> Update LemMinX version

build.gradle, src/main/java/com/langserver/devtools/intellij/lsp4jakarta/lsp/JakartaLanguageClient.java, src/main/java/com/langserver/devtools/intellij/lsp4jakarta/lsp/JakartaLanguageServer.java, src/main/resources/META-INF/lsp.xml
=> Code to consume the LSP4Jakarta function of code completion.

src/main/java/com/langserver/devtools/intellij/lsp4jakarta/lsp/JakartaLanguageClient.java, src/main/java/com/langserver/devtools/intellij/lsp4jakarta/lsp4ij/AbstractDiagnosticsCollector.java, src/main/java/com/langserver/devtools/intellij/lsp4jakarta/lsp4ij/AnnotationUtil.java, src/main/java/com/langserver/devtools/intellij/lsp4jakarta/lsp4ij/DiagnosticsCollector.java, src/main/java/com/langserver/devtools/intellij/lsp4jakarta/lsp4ij/Messages.java, src/main/java/com/langserver/devtools/intellij/lsp4jakarta/lsp4ij/PositionUtils.java, src/main/java/com/langserver/devtools/intellij/lsp4jakarta/lsp4ij/PropertiesManagerForJakarta.java, src/main/java/com/langserver/devtools/intellij/lsp4jakarta/lsp4ij/annotations/AnnotationConstants.java, src/main/java/com/langserver/devtools/intellij/lsp4jakarta/lsp4ij/annotations/AnnotationDiagnosticsCollector.java, src/main/java/com/langserver/devtools/intellij/lsp4jakarta/lsp4ij/servlet/FilterDiagnosticsCollector.java, src/main/java/com/langserver/devtools/intellij/lsp4jakarta/lsp4ij/servlet/ListenerDiagnosticsCollector.java, src/main/java/com/langserver/devtools/intellij/lsp4jakarta/lsp4ij/servlet/ServletConstants.java, src/main/java/com/langserver/devtools/intellij/lsp4jakarta/lsp4ij/servlet/ServletDiagnosticsCollector.java, src/main/resources/org/eclipse/lsp4jakarta/jdt/core/messages/messages.properties
I tried to leave the code as similar as possible to the JDT based code rather than optimize and rewrite. This is so that future support can be as simple as possible. 
Also, I should update this PR with the changes required by the Jakarta language server client API update.
=> Support for the first three diagnostics for Jakarta LS

src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java
=> Detect Liberty server.xml as indicator for Liberty project

docs/LanguageServerIntegration.md, src/main/resources/META-INF/lsp.xml, src/main/resources/META-INF/plugin.xml
Plugin didn't start after PR #115
Updating plugin.xml files with the new package name seems to fix it.
=> Rename package in plugin xml files for #114

build.gradle, src/main/java/io/openliberty/tools/intellij/liberty/lsp/LibertyLanguageServer.java, src/main/java/io/openliberty/tools/intellij/liberty/lsp/LibertyXmlServer.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp/JakartaLanguageClient.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp/JakartaLanguageServer.java, src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp/MicroProfileServer.java
=> Fix for latest JakartaClientAPI and launching LemMinX

src/main/java/io/openliberty/tools/intellij/liberty/lsp/BootstrapPropertiesFileType.java, src/main/java/io/openliberty/tools/intellij/liberty/lsp/ServerEnvFileType.java, src/main/resources/META-INF/lsp.xml
=> Narrow activation scope for LCLS config files.

src/main/java/io/openliberty/tools/intellij/actions/AddLibertyProjectAction.java, src/main/java/io/openliberty/tools/intellij/actions/LibertyGeneralAction.java, src/main/java/io/openliberty/tools/intellij/actions/LibertyProjectAction.java, src/main/java/io/openliberty/tools/intellij/actions/RemoveLibertyProjectAction.java, src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java, src/main/resources/META-INF/plugin.xml, src/main/resources/messages/LibertyBundles.properties
Resolves: https://github.com/OpenLiberty/liberty-tools-intellij/issues/128
Manually added projects are being cached in memory are not yet being persisted.
=> Introducing support for adding and removing Liberty projects.

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/annotations/AnnotationDiagnosticsCollector.java
=> Check for null value of date arg before using.

build.gradle
Signed-off-by: Matt Bowersox <m.bowersox@ibm.com>
=> Add LSP4Jakarta snapshot repo

build.gradle
Signed-off-by: Matt Bowersox <m.bowersox@ibm.com>
=> Simplify repositories block

build.gradle
Bump jsoup dependency version to address https://www.mend.io/vulnerability-database/CVE-2022-36033
=> Bump jsoup dependency

.github/workflows/build.yaml, build.gradle
Signed-off-by: Matt Bowersox <m.bowersox@ibm.com>
=> Remove lsp4jakarta build steps from GHA builds

src/main/resources/META-INF/plugin.xml
=> Limit IntelliJ version to 2022.2.x

src/main/java/io/openliberty/tools/intellij/LibertyExplorer.java, src/main/java/io/openliberty/tools/intellij/actions/LibertyGeneralAction.java
Fixes an error/exception that shows up with `runIde` all the time.
Optimize some code for running LibertyGeneralAction.
Refactor some code that use deprecated methods.
=> Small fixes, optimizations, and cleanup.

build.gradle
Signed-off-by: Matt Bowersox <m.bowersox@ibm.com>
=> Update liberty-langserver and liberty-langserver-lemminx versions

src/main/java/io/openliberty/tools/intellij/LibertyExplorer.java, src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/LanguageServersRegistry.java, src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/ServerExtensionPointBean.java, src/main/resources/META-INF/plugin.xml
Fix another warning/exception with ActionPlaces
Tested and runs properly on 2022.3 in MacOS and Windows
=> Fix launching LS with IntelliJ 2022.3

build.gradle, src/main/resources/META-INF/plugin.xml
=> Add changeNotes for 0.0.8 and update plugin description

docs/user-guide.md
noticed this when I reviewed the VSC doc. This should be an unordered list since these are sections, not steps
=> make section outline numbers into bullets

CONTRIBUTING.md, DEVELOPING.md, README.md, src/main/resources/META-INF/plugin.xml
See https://github.com/kathrynkodama/open-liberty-tools-intellij/tree/readme-java17#liberty-tools-for-intellij-idea 
Modifications to the plugin.xml file will reflect the Liberty Tools for IntelliJ marketplace description on next release.
=> Clearly document Java 17 requirement

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp/JakartaLanguageClient.java, src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp/MicroProfileLanguageClient.java, src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/LanguageClientImpl.java, src/main/resources/META-INF/lsp.xml
=> Re-enable diagnostics

src/main/java/io/openliberty/tools/intellij/liberty/lsp/LibertyXmlServer.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp/JakartaLanguageServer.java
I found the existing code a little confusing so I added the comment to explain the data structure.
=> Xmlserver cleanup

src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/LanguageServerWrapper.java
The latest LanguageServerWrapper in lsp4e is better designed than the older copy we have in the plugin. Most of the snippets of code are the same they are just rearranged to make them easier to understand. This pull request merges some of the improvements into our code.
=> Merge the useful features of latest LanguageServerWrapper into plugin

src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/LanguageServiceAccessor.java, src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/operations/diagnostics/LSPLocalInspectionTool.java
Fixes #258 
Now in `LSPLocalInspectionTool#checkFile()` logic:
1. Calls `getLanguageServers()` to ensure that the language servers are starting asynchronously but does not wait for that CompletableFuture to complete.
2. Calls ~~`getLSWrappers()`~~ `getMatchingStartedWrappers()` in order to get a list of running language server wrappers to check diagnostics for. 
The multi-step approach avoids the deadlock described in #270, since we are not waiting for the CompletableFuture in step 1 to complete anymore with the `.get()`
=> Initialize language servers when creating inspections

src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/operations/diagnostics/LSPDiagnosticsToMarkers.java
=> Refresh inspections to clear old diagnostics

src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/operations/hover/LSPTextHover.java
The plugin causes an IDE error now for some reason. Perhaps updating a dependency added a new requirement.
=> Call Application.runReadAction() when fetching hover info.

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp/JakartaLanguageClient.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/PropertiesManagerForJakarta.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/JakartaCodeActionHandler.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/annotations/AddResourceMissingNameQuickFix.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/annotations/AddResourceMissingTypeQuickFix.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/InsertAnnotationAttributesQuickFix.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/InsertAnnotationQuickFix.java
=> Initial framework to create an empty list of codeActions when the lsp4jakarta

.github/workflows/build.yaml, build.gradle, src/test/java/io/openliberty/tools/intellij/it/GradleSingleModAppTest.java, src/test/java/io/openliberty/tools/intellij/it/MavenSingleModAppTest.java, src/test/java/io/openliberty/tools/intellij/it/SingleModAppTestCommon.java, src/test/java/io/openliberty/tools/intellij/it/TestUtils.java, src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java
This PR:
- Adds Run tests action test run through the drop-down menu.
- Adds start/runTests/stop action tests run through the project pop-up menu. These tests stumbled upon knows issue : 272. They will be re-enabled when the issue is fixed.
=> Add new tests and other improvements.

src/test/java/io/openliberty/tools/intellij/it/GradleSingleModAppTest.java, src/test/java/io/openliberty/tools/intellij/it/MavenSingleModAppTest.java, src/test/java/io/openliberty/tools/intellij/it/SingleModAppTestCommon.java, src/test/java/io/openliberty/tools/intellij/it/TestUtils.java, src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java, src/test/java/io/openliberty/tools/intellij/it/fixtures/DialogFixture.java, src/test/resources/apps/gradle/single-mod-gradle-app/Dockerfile, src/test/resources/apps/gradle/single-mod-gradle-app/src/main/liberty/config/server.xml, src/test/resources/apps/maven/single-mod-maven-app/Dockerfile, src/test/resources/apps/maven/single-mod-maven-app/pom.xml, src/test/resources/apps/maven/single-mod-maven-app/src/main/liberty/config/server.xml, src/test/resources/ci/scripts/setup.sh
This PR adds:
- Basic Start with parms test.
- Run with container test running on Linux.
- Start/RunTests/Stop test using the tool window actions and the play action button.
=> Add container and start with parms and play button tests

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/JakartaCodeActionHandler.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/ModifyAnnotationProposal.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/NewAnnotationProposal.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/InsertAnnotationQuickFix.java, src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/operations/codeactions/LSPCodeActionAnnotator.java
In one or two cases I reformatted a lambda so that I could insert LOG stmts.
=> Add support for @Resource() missing type parameter quick fix for Jakarta

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/JakartaCodeActionHandler.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/ModifyModifiersProposal.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/RemoveAbstractModifierQuickFix.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/RemoveFinalModifierQuickFix.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/RemoveModifierConflictQuickFix.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/RemoveStaticModifierQuickFix.java
=> Introducing quick fixes for removing conflicting Java modifiers.

src/test/java/io/openliberty/tools/intellij/it/SingleModLibertyLSTestCommon.java, src/test/java/io/openliberty/tools/intellij/it/TestUtils.java, src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java
adds two tests:
- test type ahead completion to select a liberty feature to insert based on a partially typed feature name. (el-3.0)
- test type ahead completion to select a liberty config stanza to insert based on a partially typed config name (userInfo)
=> server.xml insertion tests

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/JakartaCodeActionHandler.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/FilterImplementationQuickFix.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/ListenerImplementationQuickFix.java
Good example of a quick fix which creates 7 different code actions.
Fixes #309
=> Quick fixes rely upon ImplementInterfaceProposal

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/JakartaCodeActionHandler.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/ExtendClassProposal.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/HttpServletQuickFix.java
Quite similar to the last one.
=> Quick fix to implement HttpServlet.

src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/LSPIJUtils.java, src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/core/StaticPropertyProviderExtensionPointBean.java, src/main/resources/META-INF/plugin.xml, src/main/resources/static-properties/jul-metadata.json
Additional needed changes discovered while fixing lsp4mp quickfixes
Remove unnecessary extension points
Add `jul-metadata.json` for `microprofile-config.properties`
=> Additional MicroProfile support and changes

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/cdi/ManagedBeanQuickFix.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/JakartaCodeActionHandler.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/ModifyAnnotationProposal.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/InsertAnnotationMissingQuickFix.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/persistence/PersistenceAnnotationQuickFix.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/CompleteFilterAnnotationQuickFix.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/CompleteServletAnnotationQuickFix.java, src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/java/corrections/proposal/ReplaceAnnotationProposal.java
All these quick fixes modify annotations. 
Fixes #304
=> Add a collection of 5 quick fixes which extend InsertAnnotationMissingQuickFix

src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/java/codeaction/JavaCodeActionContext.java, src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/java/codeaction/JavaCodeActionResolveContext.java, src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/core/java/codeaction/CodeActionHandler.java
mirror redhat-developer/intellij-quarkus#781
=> Fix IndexOutOfBoundsException

build.gradle, src/main/java/io/openliberty/tools/intellij/util/LibertyMavenUtil.java, src/main/resources/META-INF/plugin.xml
=> Update method to set custom maven home in IntelliJ 2023 and later

src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/DocumentContentSynchronizer.java
Fixes #275
Copy fix from redhat-developer/intellij-quarkus#778
=> Use better fix from intellij-quarkus for doc syncing

src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/operations/codeactions/LSPCodeActionAnnotator.java
Fixes #329 
This code initially came from LocalInspectionTool.
=> Initialize language servers before trying to utilize them

src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/LSPIJUtils.java
These changes are no longer needed after getting the proper fix with #350
=> Revert LSPIJUtils range changes from #320 and #325

src/test/java/io/openliberty/tools/intellij/it/GradleSingleModLSTest.java, src/test/java/io/openliberty/tools/intellij/it/GradleSingleModProjectTest.java, src/test/java/io/openliberty/tools/intellij/it/MavenSingleModProjectTest.java, src/test/java/io/openliberty/tools/intellij/it/SingleModProjectTestCommon.java, src/test/java/io/openliberty/tools/intellij/it/TestUtils.java, src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java, src/test/java/io/openliberty/tools/intellij/it/fixtures/DialogFixture.java, src/test/java/io/openliberty/tools/intellij/it/fixtures/ProjectFrameFixture.java
This PR:
- Adds tests to process a configuration in Debug mode (toolbar and menu).
- Adds tests that start dev mode using a configuration (toolbar and menu).
=> Add config and debugger attach tests

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp/JakartaLanguageClient.java, src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp/MicroProfileLanguageClient.java, src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/LanguageClientImpl.java
Let me know if adding that method to an Impl class makes sense. 
Fixes #336
=> Run the Jakarta special LS requests on a separate thread.

src/test/java/io/openliberty/tools/intellij/it/GradleSingleModProjectTest.java, src/test/java/io/openliberty/tools/intellij/it/MavenSingleModProjectTest.java, src/test/java/io/openliberty/tools/intellij/it/SingleModProjectTestCommon.java, src/test/java/io/openliberty/tools/intellij/it/TestUtils.java, src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java
Adds the parameter to run tests and associated validation.
Refactors common variables.
=> Expand start with parms tests

build.gradle, src/main/java/io/openliberty/tools/intellij/liberty/lsp/LibertyXmlServer.java
#370 
Contains update for LCLS CreateFile quickfix and LemMinX diagnostic bug
=> Pull LCLS M2-SNAPSHOT

src/main/java/io/openliberty/tools/intellij/actions/LibertyDevCustomStartAction.java
=> Check the build file is null before using.

src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/ConnectDocumentToLanguageServerSetupParticipant.java, src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/LSPVirtualFileWrapper.java, src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/operations/diagnostics/LSPDiagnosticsForServer.java
Mirror the last changes to redhat-developer/intellij-quarkus#833 
Prevent unnecessarily restarting the LS
=> Updates to dispose, prevent unnecessarily restarting LS

src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/operations/completion/LSIncompleteCompletionProposal.java
Added the code in the style currently in use but it could stand a rewrite.
Fixes #372
=> Add handling for variable substitution in the form ${ABC}

src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java
Enable debug tests since https://github.com/OpenLiberty/liberty-tools-intellij/pull/366 resolved #348
=> Enable debug tests

src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/LSPIJUtils.java
Addresses #405 
Refactoring other end range calls to toEndOffset breaks other features. 
Quick fixes tested: server.xml `optional` insertion, MicroProfile + Jakarta `implements` insertion, snippet creation
=> Simple patch for Out of Bounds exception

src/main/java/io/openliberty/tools/intellij/LibertyExplorer.java, src/main/java/io/openliberty/tools/intellij/LibertyModuleNode.java, src/main/java/io/openliberty/tools/intellij/actions/LibertyGeneralAction.java, src/main/resources/META-INF/plugin.xml
Fixes #126
This completes the fix for issue #272.
=> Prevent request to select project when using ctx popup-menu

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp/JakartaLanguageClient.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/PropertiesManagerForJakarta.java
=> Java cursor context

src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java
=> Handle run configurations dialog resize during config deletion.

src/main/java/io/openliberty/tools/intellij/util/LibertyGradleUtil.java
=> tiny fix for comment regex

build.gradle, src/main/java/io/openliberty/tools/intellij/liberty/lsp/LibertyConfigLanguageServer.java, src/main/java/io/openliberty/tools/intellij/liberty/lsp/LibertyXmlServer.java
Fixes #173 
Updated the regex to strip the Libery Config LS jars version
=> Fixes #173: Updated the regex to strip the Libery Config LS jars version

src/main/resources/META-INF/plugin.xml
Fixes #468 - Added link to Github issues when an error is found to assist reporting
=> Fixes #468 - Add link to Github issues when an error is found to assist reporting

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/annotations/PostConstructReturnTypeQuickFix.java, src/main/resources/META-INF/plugin.xml, src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/annotations/PostConstructAnnotationTest.java, src/test/resources/projects/maven/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/annotations/PostConstructAnnotation.java
Fixes #513 - Implemented code action for the QuickFix class PostConstructReturnTypeQuickFix.
=> Fixes #513 - Implement code action for the QuickFix class PostConstructReturnTypeQuickFix.

build.gradle
Fixes https://github.com/OpenLiberty/liberty-tools-intellij/issues/508
=> #508 Newest LCLS Version updated 

src/main/java/io/openliberty/tools/intellij/actions/LibertyDevStartAction.java, src/main/java/io/openliberty/tools/intellij/actions/LibertyDevStartContainerAction.java, src/main/java/io/openliberty/tools/intellij/util/LibertyGradleUtil.java
=> Use the Gradle config in a subdirectory or default to that in the Project directory.

build.gradle
Part of https://github.com/OpenLiberty/liberty-tools-intellij/issues/565
=> Add 23.0.12 release notes and update version to 23.0.12

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/beanvalidation/BeanValidationQuickFix.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/RemoveAnnotationsProposal.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/RemoveElementsProposal.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/jax_rs/NoResourcePublicConstructorQuickFix.java, src/main/resources/META-INF/plugin.xml, src/main/resources/org/eclipse/lsp4jakarta/jdt/core/messages/messages.properties, src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/beanvalidation/BeanValidationTest.java, src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/jaxrs/ResourceClassConstructorTest.java, src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/jaxrs/ResourceMethodTest.java
Fixes #543  --> Transform the Quick fixes related to ModifyModifiersProposal to implement the code action
=> Transform the Quick fixes related to ModifyModifiersProposal to implement the code action

build.gradle, src/main/java/io/openliberty/tools/intellij/LibertyExplorer.java, src/main/java/io/openliberty/tools/intellij/actions/LibertyProjectAction.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/AnnotationUtil.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/annotations/PostConstructReturnTypeQuickFix.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/cdi/ManagedBeanNoArgConstructorQuickFix.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/JakartaCodeActionHandler.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/InsertAnnotationQuickFix.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/RemoveModifierConflictQuickFix.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/jax_rs/NonPublicResourceMethodQuickFix.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/persistence/PersistenceEntityQuickFix.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/HttpServletQuickFix.java, src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp/MicroProfileMatcher.java, src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/MicroProfilePostStartupActivity.java, src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/java/codeaction/InsertAnnotationAttributeQuickFix.java, src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/java/codeaction/InsertAnnotationMissingQuickFix.java, src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/java/validators/annotations/AnnotationValidator.java, src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/project/PsiMicroProfileProject.java, src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/project/PsiMicroProfileProjectManager.java, src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/config/java/MicroProfileConfigASTValidator.java, src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/config/java/NoValueAssignedToPropertyQuickFix.java, src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/config/java/PropertyNameData.java, src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/core/java/codeaction/JavaCodeActionDefinition.java, src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/core/java/corrections/JavaDiagnosticsDefinition.java, src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/faulttolerance/java/MicroProfileFaultToleranceASTValidator.java, src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/health/java/ImplementHealthCheckQuickFix.java, src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/metrics/java/ApplicationScopedAnnotationMissingQuickFix.java, src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/openapi/java/MicroProfileGenerateOpenAPIOperation.java, src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java, src/main/resources/META-INF/lsp.xml
Add the latest fixes to the origin branch.
Rethrow index related exceptions to the action can be retried.
Use the microprofile/propertiesUpdated message to refresh properties and Java diagnostics.
=> Use lsp4ij 1201 January

.github/workflows/build.yaml
=> Specify the correct tag for lsp4ij

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/cdi/RemoveInvalidInjectParamAnnotationQuickFix.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/RemoveParamAnnotationQuickFix.java, src/main/resources/META-INF/plugin.xml, src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/cdi/ManagedBeanTest.java
Fixes #589 
Refactored and modified the test cases
=> Fixes #589 - Refactoring of Quick Fix class RemoveInvalidInjectParamAnnotationQuickFix

.github/workflows/build.yaml, build.gradle, src/test/java/io/openliberty/tools/intellij/it/SingleModLibertyLSTestCommon.java, src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java
I also copied in some code from main that is related to gradle and maven so that the merging with main will be easier in the future.
Fixes #625
Fixes #624 
Fixes #623
=> Fix three test cases that fail using new lsp4ij

build.gradle
=> Update versions of lemminx and lcls

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/cdi/ManagedBeanConstructorQuickFix.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/cdi/ManagedBeanQuickFix.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/InsertAnnotationMissingQuickFix.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/persistence/PersistenceAnnotationQuickFix.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/CompleteFilterAnnotationQuickFix.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/CompleteServletAnnotationQuickFix.java, src/main/resources/META-INF/plugin.xml, src/main/resources/org/eclipse/lsp4jakarta/jdt/core/messages/messages.properties, src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/cdi/ManagedBeanConstructorTest.java, src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/cdi/ManagedBeanTest.java, src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/persistence/JakartaPersistenceTest.java, src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/servlet/JakartaServletTest.java, src/test/resources/projects/maven/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/servlet/DuplicateAttributeWebFilter.java, src/test/resources/projects/maven/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/servlet/DuplicateAttributeWebServlet.java, src/test/resources/projects/maven/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/servlet/InvalidWebFilter.java
=> Fixes #577 - Quick Fixes which extend Insert annotation missing quick fix .

src/main/resources/META-INF/lsp.xml
The value is in seconds.
Fixes #648
=> Increase timeout before shutting down language servers

src/main/resources/messages/LibertyBundles.properties
=> Dmuelle patch 1

src/test/java/io/openliberty/tools/intellij/it/SingleModJakartaLSTestCommon.java, src/test/java/io/openliberty/tools/intellij/it/SingleModLibertyLSTestCommon.java, src/test/java/io/openliberty/tools/intellij/it/SingleModMPLSTestCommon.java
=> Enable tests for quick fixes

src/main/resources/META-INF/lsp.xml
=> Update descriptions in LS Console

build.gradle
From the note in box which was reviewed.
Part of #679
=> Add release notes for 24.0.3

DEVELOPING.md, README.md, docs/user-guide.md
=> Add LSP console description to DEVELOPING.md

build.gradle
- updated version to 24.0.3
- added line for 2023.3 support
- edited line for MP completion
- changed order of bullet points for "Notable changes" section
- added note regarding performance issue
- fixed spacing in old release notes
=> Update version and modify release notes

src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunSettingsEditor.form, src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunSettingsEditor.java, src/main/resources/messages/LibertyBundles.properties, src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java
=> Update message in Gradle Run/Debug configuration editor

src/main/java/io/openliberty/tools/intellij/LibertyExplorer.java, src/test/resources/ci/scripts/run.sh
Fixes #674 
Fixed Exception Slow operations are prohibited on EDT
=> Fix Exception Slow operations are prohibited on EDT

build.gradle, src/main/resources/META-INF/plugin.xml, src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/annotations/GeneratedAnnotationTest.java, src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/annotations/PostConstructAnnotationTest.java, src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/annotations/PreDestroyAnnotationTest.java, src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/annotations/ResourceAnnotationTest.java, src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/beanvalidation/BeanValidationTest.java, src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/cdi/ManagedBeanConstructorTest.java, src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/cdi/ManagedBeanTest.java, src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/core/BaseJakartaTest.java, src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/di/DependencyInjectionTest.java, src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/di/MultipleConstructorInjectTest.java, src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/jaxrs/ResourceClassConstructorTest.java, src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/jaxrs/ResourceMethodTest.java, src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/jsonb/JsonbDiagnosticsCollectorTest.java, src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/jsonp/JakartaJsonpTest.java, src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/persistence/JakartaPersistenceTest.java, src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/servlet/JakartaServletTest.java, src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/websocket/JakartaWebSocketTest.java
Resolves https://github.com/OpenLiberty/liberty-tools-intellij/issues/722 and https://github.com/OpenLiberty/liberty-tools-intellij/issues/739.
=> Upgrade to IntelliJ 2024.1.1 and address issues with the Jakarta EE unit tests.

.github/workflows/build.yaml
=> 608 - Use lsp4 i jmarket 2024.1 intellij support

.github/workflows/build.yaml, build.gradle, src/main/resources/META-INF/plugin.xml
- Updated LSP4ij version.
- Removed redhat telemetry dependency
- Added gson test dependency to fix UI test failures.
=> Issue608 - Support intellij 2024.1 version

.github/workflows/build.yaml
The tag has been added to the MicroShed project.
=> Use lsp4ij 0.0.5

src/main/java/io/openliberty/tools/intellij/actions/LibertyDevRunTestsAction.java, src/main/java/io/openliberty/tools/intellij/actions/LibertyDevStartAction.java, src/main/java/io/openliberty/tools/intellij/actions/LibertyDevStartContainerAction.java, src/main/java/io/openliberty/tools/intellij/actions/LibertyDevStopAction.java, src/main/java/io/openliberty/tools/intellij/util/LibertyActionUtil.java
I'm not sure the github action tests Windows fully. Code refactored for clarity in two of the five files. 
Fixes #797
=> Run Liberty Start commands on separate thread

src/main/java/io/openliberty/tools/intellij/util/LibertyActionUtil.java
=> Change messages to debug or error

build.gradle
=> Updated the build.gradle to support 0.0.1 lsp4ij versions.

build.gradle, src/main/java/io/openliberty/tools/intellij/lsp4mp/MicroProfileDeploymentSupport.java, src/main/java/io/openliberty/tools/intellij/lsp4mp/MicroProfileProjectService.java, src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp/MicroProfileLanguageClient.java, src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/classpath/ClasspathResourceChangedManager.java, src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/AbstractAnnotationTypeReferencePropertiesProvider.java, src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/AbstractTypeDeclarationPropertiesProvider.java, src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/PropertiesManagerForJava.java, src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/java/diagnostics/DiagnosticsHandler.java, src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/java/hover/PropertiesHoverParticipant.java, src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/project/PsiMicroProfileProject.java, src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/project/PsiMicroProfileProjectManager.java, src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/core/java/codeaction/JavaCodeActionDefinition.java, src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/core/java/validators/MultiASTVisitor.java, src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/health/MicroProfileHealthConstants.java, src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/health/java/HealthAnnotationMissingQuickFix.java, src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/health/java/MicroProfileHealthDiagnosticsParticipant.java, src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/jaxrs/java/DefaultJaxRsInfoProvider.java, src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/jaxrs/java/JaxRsCodeLensParticipant.java, src/main/java/io/openliberty/tools/intellij/util/LibertyToolPluginDisposable.java, src/main/resources/META-INF/lsp.xml
Fixes #775 - Quick fix option is not working for Microprofile quickfix 
Fixes #795  - Update lsp4mp4ij component from intellij Quarkus (updated with the latest lsp4mp4ij available in main branch)
=> Issue795 & issue 775 : Updated lsp4mp4ij component from intellij Quarkus and Resolved MP quickfix issue

README.md, build.gradle, docs/user-guide.md
Resolves https://github.com/OpenLiberty/liberty-tools-intellij/issues/746
=> Update version and docs for 24.0.6

src/test/java/io/openliberty/tools/intellij/it/SingleModMPLSTestCommon.java
Changed a diagnostic message to fix a UI test.
testMPDiagnosticsInJavaPart()
=> issue 795 - Update lsp4mp4ij

src/test/java/io/openliberty/tools/intellij/it/SingleModMPLSTestCommon.java
updated the expected hover message. (testMicroProfileConfigHover)
=> issue 760 - UI tests failures after lsp4ij plugin integration.

build.gradle, src/main/java/io/openliberty/tools/intellij/liberty/lsp/LibertyConfigLanguageServer.java, src/main/java/io/openliberty/tools/intellij/liberty/lsp/LibertyXmlServer.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp/JakartaLanguageServer.java, src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp/MicroProfileServer.java
=> Issue 760 - UI test failure in latest nightly build.

src/main/java/io/openliberty/tools/intellij/LibertyModule.java, src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunManagerListener.java
=> Simplify the API for custom params in LibertyModule

build.gradle
Updated to latest lsp4ij version 0.0.2.
Fixes #844
=> Hover message is randomly blank or there is a helpful message

.github/workflows/pr-slack-notification.yaml
Fixes https://github.com/OpenLiberty/liberty-tools-intellij/issues/803
Added a new YAML file, `pr-slack-notification.yaml,` for sending Slack notifications based on cron job runs.
Fixes https://github.com/OpenLiberty/liberty-tools-intellij/issues/810
At the end of `pr-slack-notification.yaml`, I have added one more job called `slack-notification`, which is used to trigger Slack Workflow Builder as a fix for the issue https://github.com/OpenLiberty/liberty-tools-intellij/issues/810
=> Fix for Sending Notification to Slack Channel on List of PRs in LSP4IJ

src/main/java/io/openliberty/tools/intellij/util/LibertyGradleUtil.java
The old code was used as inspiration for new code so this should be cleaned up to be more readable.
Fixes #869
=> Refactor gradle command generator to return at the end of the method

.github/workflows/cronJob.yaml
Cron job to runs at 15:45 UTC every Monday through Friday, which is 9:15 PM IST and 11:45 AM EST.
=> Changed Cron job execution time

src/main/java/io/openliberty/tools/intellij/actions/LibertyProjectAction.java, src/main/java/io/openliberty/tools/intellij/actions/LibertyProjectChooserDialog.java, src/main/java/io/openliberty/tools/intellij/actions/RunLibertyDevTask.java
=> Replaced showChooseDialog with MessageDialog class

src/test/java/io/openliberty/tools/intellij/it/SingleModJakartaLSTestCommon.java, src/test/java/io/openliberty/tools/intellij/it/SingleModLibertyLSTestCommon.java, src/test/java/io/openliberty/tools/intellij/it/SingleModMPLSTestCommon.java, src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java
There is no issue for this fix but it affects several of the issues we have open for automated testing. For instance Anusree was looking at an issue on Windows and she noticed this problem.
Fixes #886
=> Examine the UI for IntelliJ indexing and wait

.github/workflows/build.yaml, build.gradle, src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/command/MicroprofileOpenURIAction.java
PR to address review comments on feature branch merge
=> Addressed review comments

DEVELOPING.md
=> Document Recording all test videos 

build.gradle
Resolves https://github.com/OpenLiberty/liberty-tools-intellij/issues/957
=> Upgrading to LSP4iJ 0.5.0.

src/test/resources/files/smNLTRestProject/gradle/pluginsDSLOnlyDepDef.build.gradle, src/test/resources/files/smNLTRestProject/maven/pom.xml, src/test/resources/projects/gradle/sampleGradleMPLSApp/build.gradle, src/test/resources/projects/gradle/singleModGradleMP/build.gradle, src/test/resources/projects/maven/jakarta-sample/pom.xml, src/test/resources/projects/maven/singleModMavenMP/pom.xml
=> Updated LGP and LMP versions in Sample projects used in UI tests

NOTICE, README.md, build.gradle, docs/user-guide.md
- Updated version to 24.0.9
- Updated doc to reflect support for IntelliJ 2024.1 only
- Added release notes for 24.0.9
- Removed MicroShed LSP4IJ dependency from NOTICE file
=> Updates for version, doc, release notes, and NOTICE file

DEVELOPING.md, docs/LSP4IJ-Continuous-Integration.md, docs/user-guide.md
- Added table to record tested LSP4IJ versions
- Updated table of contents in DEVELOPING.md
- Edited a sentence in LSP4IJ-Continuous-Integration.md
View changes on the docs in this branch: https://github.com/TrevCraw/liberty-tools-intellij/tree/24.0.9-doc-updates
=> Various doc updates

src/test/resources/files/smNLTRestProject/maven/pom.xml, src/test/resources/projects/maven/jakarta-sample/pom.xml, src/test/resources/projects/maven/singleModMavenMP/pom.xml
=> Suppress the signature verification warnings

.github/workflows/cronJob.yaml
=> Added version 24.0.9 to the existing LTI tag 

DEVELOPING.md
Fixes #1002 
Updated the DEVELOPING.md - Removed the steps for building lsp4ij code from Microshed.
=> Updated the DEVELOPING.md - Removed the steps for building lsp4ij code from Microshed

build.gradle
Resolves https://github.com/OpenLiberty/liberty-tools-intellij/issues/1022
=> Upgrade to LSP4IJ 0.7.0.

build.gradle
Part of #1006 
Update LCLS version to 2.2
=> Update LCLS version to 2.2

build.gradle
Resolves https://github.com/OpenLiberty/liberty-tools-intellij/issues/1016 and https://github.com/OpenLiberty/liberty-tools-intellij/issues/1057.
=> Upgrade to LSP4MP 0.13.0.

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/ServletConstants.java
=> servlet.FilterDiagnosticsCollector : Removed unused unqualified names 

README.md, docs/user-guide.md
Resolves https://github.com/OpenLiberty/liberty-tools-intellij/issues/1073
=> LSP4IJ documentation improvements

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/AbstractDiagnosticsCollector.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/beanvalidation/BeanValidationQuickFix.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/RemoveParamAnnotationQuickFix.java, src/main/resources/io/openliberty/tools/intellij/lsp4jakarta/messages/messages.properties, src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/beanvalidation/BeanValidationTest.java, src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/cdi/ManagedBeanTest.java
=> Display short names for Quick fixes - Issue#870

build.gradle
Resolves https://github.com/OpenLiberty/liberty-tools-intellij/issues/1128
=> Upgrade to LSP4IJ 0.8.1.

gradle.properties
Part of #1005
Updated the compatibility level to `2024.3`
=> Updated the ide version to 2024.3

build.gradle
Fixes #1154 
Part of the release process. Still need to update version to 24.0.12 after testing.
=> Update version to 24.0.12-SNAPSHOT

README.md, docs/user-guide.md
Resolves https://github.com/OpenLiberty/liberty-tools-intellij/issues/1160
Note: Do **NOT** merge until LTI 24.0.12 is ready for release.
=> Update GitHub documentation for LTI 24.0.12.

.github/workflows/cronJob.yaml
Fixes #1209
Added LTI version `24.0.12` to the existing `tag`
=> Add LTI version 24.0.12 

build.gradle
Resolves https://github.com/OpenLiberty/liberty-tools-intellij/issues/1252
=> Upgrade to LSP4IJ 0.9.0.

gradle.properties
Fixes #1255 
Manual testing was done using the 251.14649.49 EAP version and the issue are documented in #1233
=> IntelliJ IDE Version changed to 251.14649.49 EAP

src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java
=> Add the menuAction support for version 2025.1

.github/workflows/cronJob.yaml
=> Change 24.0.12 tag in Cron Job to 24.0.12-lsp4ijFix branch

build.gradle, docs/user-guide.md
=> Upgrade to LSP4IJ 0.11.0.

build.gradle
Fixes #1262 
Tested and verified with 2.2.1, all issues listed in #1262 and every case is working as expected.
Changed LCLS version to 2.2.1
=> Changed LCLS version to 2.2.1

build.gradle
Fixes #1305 
Fix to resolve plugin dependency failure for nightly builds
=> Fix to resolve plugin dependency failure for nightly builds

src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java
Noticed this paragraphing problem and I found it confusing. Just fixed it up for readability.
Fixes #1317
=> Fix paragraphing for readability

build.gradle, docs/user-guide.md
Resolves https://github.com/OpenLiberty/liberty-tools-intellij/issues/1315
=> Upgrade to LSP4IJ 0.12.0.

src/main/java/io/openliberty/tools/intellij/LibertyPluginIcons.java
=> Adding a '/' to the Gradle path for consistency with the others.

src/main/java/io/openliberty/tools/intellij/liberty/lsp/LibertyConfigLanguageServer.java, src/main/java/io/openliberty/tools/intellij/liberty/lsp/LibertyXmlServer.java, src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp/JakartaLanguageServer.java, src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp/MicroProfileServer.java
Resolves #1322
See Quarkus Tools PR https://github.com/redhat-developer/intellij-quarkus/pull/1444 which just adopted this API.
=> Switch to OSProcessStreamConnectionProvider as the recommended API for language servers.

build.gradle, docs/user-guide.md
Resolves https://github.com/OpenLiberty/liberty-tools-intellij/issues/1328
=> Upgrade to LSP4IJ 0.13.0.

README.md, build.gradle, docs/user-guide.md
- Updated version to 25.0.5
- Added release notes
- Updated supported IntelliJ versions
- Updated tested LSP4IJ versions
=> 25.0.5 Release Prep

.github/workflows/build.yaml, src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java
Fixes https://github.com/OpenLiberty/liberty-tools-intellij/issues/1360
Resolved NPE and application start failure with LTI during Intellij fresh installs
=> Changed Terminal Engine to CLASSIC using reflection

gradle.properties
Fixes #1375 
Tested with LCLS 2.3.2, no issues identified.
=> Added support for LCLS 2.3.2

README.md, build.gradle, docs/user-guide.md, src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java
Fixes #1374 
You can check the commit history of 25.0.8 here: https://github.com/OpenLiberty/liberty-tools-intellij/commits/25.0.8/
=> Move 25.0.8 fix release changes to main

README.md, build.gradle, docs/user-guide.md
- Updated version to 25.0.9
- Added release notes
- Updated LSP4IJ tested versions
- Other doc updates
=> 25.0.9 Release Prep

README.md, build.gradle, docs/user-guide.md
- Added some new release note items for 25.0.9
- Cleaned up 25.0.8 release notes
- Documented support for IntelliJ Ultimate
- Minor grammatical edits
=> 25.0.9 doc and release note updates
