build.gradle
src/main/java/io/openliberty/tools/intellij/LibertyActionNode.java
src/main/java/io/openliberty/tools/intellij/LibertyDevToolWindowFactory.java
src/main/java/io/openliberty/tools/intellij/LibertyExplorer.java
src/main/java/io/openliberty/tools/intellij/LibertyProjectNode.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyDevCustomStartAction.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyDevRunTestsAction.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyDevStartAction.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyDevStopAction.java
src/main/java/io/openliberty/tools/intellij/actions/RefreshLibertyToolbar.java
src/main/java/io/openliberty/tools/intellij/actions/ViewEffectivePom.java
src/main/java/io/openliberty/tools/intellij/actions/ViewGradleConfig.java
src/main/java/io/openliberty/tools/intellij/actions/ViewIntegrationTestReport.java
src/main/java/io/openliberty/tools/intellij/actions/ViewTestReport.java
src/main/java/io/openliberty/tools/intellij/actions/ViewUnitTestReport.java
src/main/java/io/openliberty/tools/intellij/util/Constants.java
src/main/java/io/openliberty/tools/intellij/util/LibertyActionUtil.java
src/main/java/io/openliberty/tools/intellij/util/LibertyGradleUtil.java
src/main/java/io/openliberty/tools/intellij/util/LibertyMavenUtil.java
src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java
src/main/java/io/openliberty/tools/intellij/util/TreeDataProvider.java
src/main/resources/META-INF/plugin.xml

Fix for #2 
- updated groupId to `io.openliberty.tools`
- refactored package name to `io.openliberty.tools.intellij`
- modified `testCompile` to [`testImplementation`](https://github.com/OpenLiberty/open-liberty-tools-intellij/compare/master...kathrynkodama:dev?expand=1#diff-c197962302397baf3a4cc36463dce5eaR16) to resolve the following warning `The testCompile configuration has been deprecated for dependency declaration. This will fail with an error in Gradle 7.0. Please use the testImplementation configuration instead.`

refactored name and updated groupId

---

src/main/java/io/openliberty/tools/intellij/actions/LibertyDevStartAction.java
src/main/java/io/openliberty/tools/intellij/util/LibertyActionUtil.java

Fix for #10 
Use the built in [`ShellTerminalWidget.executeCommand`](https://github.com/JetBrains/intellij-community/blob/master/plugins/terminal/src/org/jetbrains/plugins/terminal/ShellTerminalWidget.java#L121) function for new terminal sessions. 
For terminal sessions that already exist, use the [widget connector](https://gitlab.com/zipizap/jediterm/blob/master/src-terminal/com/jediterm/terminal/TtyConnector.java#L20) to send a new line character followed by the command.

fix for terminal init

---

src/main/java/io/openliberty/tools/intellij/LibertyExplorer.java
src/main/java/io/openliberty/tools/intellij/actions/ExecuteLibertyDevTask.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyDevCustomStartAction.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyDevRunTestsAction.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyDevStartAction.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyDevStopAction.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyToolbarActionGroup.java
src/main/java/io/openliberty/tools/intellij/actions/RefreshLibertyToolbar.java
src/main/java/io/openliberty/tools/intellij/actions/ViewEffectivePom.java
src/main/java/io/openliberty/tools/intellij/actions/ViewGradleConfig.java
src/main/java/io/openliberty/tools/intellij/actions/ViewIntegrationTestReport.java
src/main/java/io/openliberty/tools/intellij/actions/ViewTestReport.java
src/main/java/io/openliberty/tools/intellij/actions/ViewUnitTestReport.java
src/main/java/io/openliberty/tools/intellij/util/TreeDataProvider.java

Fix for #17 
Redraw the actionToolbar component and the tree component upon hitting refresh.  Now when the user selects refresh, the collapse/expand all options in the toolbar react right away (previously you had to select a tree node in order for them to register the new tree view), and the line separating the toolbar and the tree view is maintained (previously it would occasionally disappear upon hitting refresh).

fix for refresh button

---

src/main/java/io/openliberty/tools/intellij/LibertyExplorer.java
src/main/java/io/openliberty/tools/intellij/actions/RefreshLibertyToolbar.java
src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java

- added text when tree is null
- improved error handling when plugin cannot read build files

added text for when tree is null, improved error handling

---

src/main/java/io/openliberty/tools/intellij/LibertyExplorer.java

Fixes #33 
Adds a key listener for `Enter` key that triggers the corresponding actions

add enter key listener

---

src/main/java/io/openliberty/tools/intellij/actions/LibertyDevCustomStartAction.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyDevRunTestsAction.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyDevStartAction.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyDevStartContainerAction.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyDevStopAction.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyGeneralAction.java
src/main/java/io/openliberty/tools/intellij/actions/ViewEffectivePom.java
src/main/java/io/openliberty/tools/intellij/actions/ViewGradleConfig.java
src/main/java/io/openliberty/tools/intellij/actions/ViewIntegrationTestReport.java
src/main/java/io/openliberty/tools/intellij/actions/ViewTestReport.java
src/main/java/io/openliberty/tools/intellij/actions/ViewUnitTestReport.java

We do not currently support starting a Liberty action from anywhere other than the Liberty tool window as the plugin requires knowledge of the project context. Display a popup warning to users if they try to run Liberty actions from the main Action menu (accessible via Shift > Shift).

Display warning message if runs Liberty action from main Actions menu

---

src/main/java/io/openliberty/tools/intellij/LibertyExplorer.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyToolbarActionGroup.java
src/main/java/io/openliberty/tools/intellij/actions/RunLibertyDevTask.java

Fixes #57 
Tree parameter is populated with the list of Open Liberty projects detected in the workspace and the dev mode actions able to run against these projects.  Only display the tree view actions in the toolbar (ie. expandAll and collapseAll) if the tree parameter is not null.

Add null check for tree view

---

README.md
build.gradle
docs/GettingStarted.md
src/main/resources/META-INF/plugin.xml

Fixes #64 
To test the name change, go to IntelliJ IDEA -> Preferences -> Plugins -> Gear icon -> Install plugin from disk and navigate to the zip file attached.
[open-liberty-tools-intellij-0.0.7.zip](https://github.com/OpenLiberty/liberty-tools-intellij/files/9318455/open-liberty-tools-intellij-0.0.7.zip)

Rename to Liberty Tools and bump version to 0.0.7

---

build.gradle
src/main/java/io/openliberty/tools/intellij/LibertyExplorer.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyDevCustomStartAction.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyDevRunTestsAction.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyDevStartAction.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyDevStartContainerAction.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyDevStopAction.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyGeneralAction.java
src/main/java/io/openliberty/tools/intellij/actions/RefreshLibertyToolbar.java
src/main/java/io/openliberty/tools/intellij/actions/RunLibertyDevTask.java
src/main/java/io/openliberty/tools/intellij/actions/ViewIntegrationTestReport.java
src/main/java/io/openliberty/tools/intellij/actions/ViewTestReport.java
src/main/java/io/openliberty/tools/intellij/actions/ViewUnitTestReport.java
src/main/java/io/openliberty/tools/intellij/util/LibertyActionUtil.java
src/main/java/io/openliberty/tools/intellij/util/LibertyGradleUtil.java
src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java

Some general maintenance/fixes related to the Liberty dashboard code:
- Bump to IntelliJ 2021.3.2 and Java 11 (tried bumping to Java 17 but ran into errors, see https://github.com/OpenLiberty/liberty-tools-intellij/issues/96#issuecomment-1267360719)
- Standardize logging naming
- Fix for Gradle project names

Maintenance and fixes for Liberty Dashboard

---

build.gradle

Mend reported this CVE: https://github.com/advisories/GHSA-269g-pwp5-87pp
JUnit dependency should be bumped to version 4.13.1. 
We can also remove the JUnit dependency temporarily, since there are no automated tests yet.

Bump and temporarily remove junit dependency

---

.github/workflows/build.yaml
.run/liberty-tools-intellij [runIde].run.xml
CONTRIBUTING.md
README.md
settings.gradle

Ensure the plugin builds correctly
Also fix name references from `open-liberty-tools-intellij` to `liberty-tools-intellij`
[Sample build](https://github.com/evie-lau/liberty-tools-intellij/actions/runs/3348698256)

Build project in Github Actions

---

src/main/java/io/openliberty/tools/intellij/actions/LibertyDevCustomStartAction.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyDevStartAction.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyDevStartContainerAction.java
src/main/resources/messages/LibertyBundles.properties

Resolves #107
Allow configuring build file/dir for custom start command. Update command description for custom start
NOTE: Currently unable to test custom start command for Gradle because of #63

Custom Start updates for user-defined build file/dir

---

src/main/java/io/openliberty/tools/intellij/actions/LibertyGeneralAction.java
src/main/java/io/openliberty/tools/intellij/actions/ViewEffectivePom.java
src/main/java/io/openliberty/tools/intellij/actions/ViewGradleConfig.java
src/main/java/io/openliberty/tools/intellij/actions/ViewIntegrationTestReport.java
src/main/java/io/openliberty/tools/intellij/actions/ViewTestReport.java
src/main/java/io/openliberty/tools/intellij/actions/ViewUnitTestReport.java
src/main/resources/messages/LibertyBundles.properties

Resolves: https://github.com/OpenLiberty/liberty-tools-intellij/issues/79
With some refactoring, similar code for collecting the build files in LibertyExplorer could be shared, but I didn't attempt that in this PR. Not sure about the text for the labels on the dialog box. Please suggest improvements.

Add support for "shift + shift" IntelliJ tool window.

---

.github/workflows/build.yaml

Adding this so we can make sure `gradle buildPlugin` works on PRs to `ls-integration` branch

Allow github actions build on PRs for ls-integration

---

src/main/java/io/openliberty/tools/intellij/liberty/lsp/BootstrapPropertiesFileType.java
src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp/MicroProfileConfigFileType.java
src/main/resources/META-INF/lsp.xml

Followup on #134, ran into an exception when launching the plugin
```
com.intellij.diagnostic.PluginException: Incorrect language specified in <fileType> for bootstrap.properties file, should be null, actual BootstrapProperties [Plugin: open-liberty.intellij]
```
- Fix BootstrapPropertiesFileType to return its language for our filtered `bootstrap.properties` files
- Assign `MicroProfileConfigProperties` as language type for its respective files
Since MP Config properties is already specifically filtered to `microprofile-config*.properties` files, there seems to be no risk of incorrect language assignment to other `.properties` files

Return filetype languages for bootstrap and MP config files

---

src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/operations/completion/LSIncompleteCompletionProposal.java

Range should be start offset, end offset. I.e. start<=end.
Fixes #141

Generate valid range when grabbing text from document for replacement during completion

---

build.gradle
src/main/java/io/openliberty/tools/intellij/actions/LibertyDevStartAction.java
src/main/java/io/openliberty/tools/intellij/util/LibertyGradleUtil.java
src/main/java/io/openliberty/tools/intellij/util/LibertyMavenUtil.java
src/main/resources/META-INF/plugin.xml

This task adds the features for Gradle and Maven settings for Intellij #39 . 
allows end-users specify:
- Bundled (use default mvn)
- Maven wrapper (use mvnw)
- "..." -> Custom maven
allows end-users specify:
- "wrappers" -> gradle-wrapper / wrapper
- "Specific location" -> Custom/Default Gradle
- All tests so far were done on Mac. It's necessary to cover Windows and Linux environments!

Support for maven and gradle wrappers

---

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/annotations/AnnotationDiagnosticsCollector.java

When package name is invalid findPackage() returns null. Skip and continue finding diagnostics.
Fixes #144 and maybe #132

Check for null due to bad package name.

---

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/annotations/AnnotationDiagnosticsCollector.java

I wasn't able to reproduce the issue but this is the fix required by the `suffix` exception. This method is called in other situations so it is best to fix it on the called side rather than the calling side.
Fixes #148

In isValidAnnotation() check for null in input.

---

src/main/java/io/openliberty/tools/intellij/util/LibertyGradleUtil.java
src/main/java/io/openliberty/tools/intellij/util/LibertyMavenUtil.java

This is a fix for the issue: https://github.com/OpenLiberty/liberty-tools-intellij/issues/154
Including double quotes, we allow spaces in the path for Gradle/Maven executables.
This was tested over Mac and Windows environments.

Including double quotes to escape spaces in paths

---

src/main/java/io/openliberty/tools/intellij/LibertyProjectSettings.java
src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java
src/main/resources/META-INF/plugin.xml

Resolves: https://github.com/OpenLiberty/liberty-tools-intellij/issues/129
Example of `liberty-project-settings.xml`:
```
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
<component name="LibertyProjectSettings">
<option name="customLibertyProjects">
<set>
<option value="$PROJECT_DIR$/start/pom.xml" />
</set>
</option>
</component>
</project>
```
IntelliJ is parameterizing the path value when it saves it to the file. This should mean that the user can move their IntelliJ project to another directory after they've manually added/removed Liberty projects and it should still be able to resolve the persisted path.

Persist manually added/removed projects across IntelliJ sessions.

---

src/main/java/io/openliberty/tools/intellij/LibertyExplorer.java
src/main/java/io/openliberty/tools/intellij/LibertyModule.java
src/main/java/io/openliberty/tools/intellij/LibertyModuleNode.java
src/main/java/io/openliberty/tools/intellij/LibertyModules.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyDevCustomStartAction.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyDevRunTestsAction.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyDevStartAction.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyDevStartContainerAction.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyDevStopAction.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyGeneralAction.java
src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunConfiguration.java
src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunConfigurationFactory.java
src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunConfigurationOptions.java
src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunConfigurationType.java
src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunManagerListener.java
src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunSettingsEditor.form
src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunSettingsEditor.java
src/main/java/io/openliberty/tools/intellij/util/Constants.java
src/main/java/io/openliberty/tools/intellij/util/DebugModeHandler.java
src/main/java/io/openliberty/tools/intellij/util/LibertyActionUtil.java
src/main/java/io/openliberty/tools/intellij/util/LibertyGradleUtil.java
src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java
src/main/resources/META-INF/plugin.xml
src/main/resources/messages/LibertyBundles.properties

Fixes #110 and #108 
Contributes new Liberty run/debug config
Start... command will now open a new run config, which will allow users to specify custom parameters. 
Opened #160, #163 and #167 for enhancements

Liberty run and debug configuration

---

src/main/java/io/openliberty/tools/intellij/LibertyModule.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyGeneralAction.java
src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java

Fixes #143 
Associates each Liberty module with a ShellTerminalWidget (terminal instance). 
Also improved the check for whether we should run the stop dev mode and run tests action by using `widget.hasRunningCommands()`.  This returns true if there are running commands on the corresponding terminal instance. 

Track terminal for each Liberty module

---

src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/LanguageServerWrapper.java

Exception on line 342 will cause messageBusConnection to be used before being set.

Check for null before using messageBusConnection.

---

src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/LanguageServersRegistry.java

No exceptions when typing ctrl-space before the language servers start up.
Fixes #181

Check for null when language is not found.

---

src/main/java/io/openliberty/tools/intellij/LibertyExplorer.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyGeneralAction.java
src/main/java/io/openliberty/tools/intellij/actions/RunLibertyDevTask.java
src/main/java/io/openliberty/tools/intellij/util/Constants.java
src/main/resources/messages/LibertyBundles.properties

Fixes #190 
Through the shift+shift/go to action IntelliJ menu, always enable the "Liberty: Run Liberty action" action. 
When running through the shift+shift/go to action IntelliJ menu, prompt users with a selection of available Liberty actions:
Then, users are prompted with the project they want to run the previously selected action on:
Also fixed the bug where when the user runs an action using the "Run" icon from the tool window for the first time, it no longer fails with an NPE.

Enable run liberty action from go to action menu

---

src/main/resources/META-INF/lsp.xml

Temp fixes for NPEs from #168
Will need to be re-enabled once we fix using custom languages with `<fileType>`

Disable go-to handler

---

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp/JakartaLanguageClient.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/PropertiesManagerForJakarta.java

In this pull request I've refactored the code to look more like the lsp4mp and lsp4jakarta clients. This should make comparing the code bases easier in the future when we need to scan one looking for fixes to apply to the other. Or, if performing dual maintenance, the code can more easily be ported across.
Also, note a functional change. Formerly the classpath request handled on the communication thread since the work appeared small. Now we move the work to the completable futures thread pool like it is handled on the other language server clients.
Fixes #191

Use lsp4jakarta extended API to specify package and class names required for a new class snippet

---

src/main/java/io/openliberty/tools/intellij/util/LibertyGradleUtil.java
src/main/resources/messages/LibertyBundles.properties

This is a fix for https://github.com/OpenLiberty/liberty-tools-intellij/issues/197 following the strategy we agreed during scrum, that is, throw a nice message error in the case gradle settings is null.

Including an exception for when gradle settings is null

---

build.gradle
src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/operations/hover/LSPTextHover.java
src/main/resources/META-INF/lsp.xml

Part of #147 
- Enables hover from LemMinX + Liberty LemMinX extension. 
- Fixes write-unsafe context error when opening external links (e.g. server.xsd) from hover
- Bump IntelliJ Gradle plugin to latest version
- Fixes https://github.com/OpenLiberty/liberty-tools-intellij/issues/242, TimeoutException occurs on first hover in a fresh IntelliJ session.
Hover on server.xml schema elements. Note server.xsd is a click-able link, will open server.xsd file in-editor.
Hover on feature names for feature description.
Alternatively, users can select the 3 dots -> "Open in documentation tool window" (native IntelliJ mechanism).
Now hover text shows up in documentation tool window rather than over the file itself.
I did not observe any conflicts between the native IntelliJ hover support in existing …

Enable hover for server.xml files

---

src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/LanguageServiceAccessor.java

Mainly to check in the deprecated API fix pointed out by Evie.

Fix issues flagged by IntelliJ including deprecated API and invalid javadoc

---

src/main/java/io/openliberty/tools/intellij/util/LibertyGradleUtil.java

Signed-off-by: Jenő Tobak <tobakjeno@gmail.com>
fixes [#256](https://github.com/OpenLiberty/liberty-tools-intellij/issues/257)

Use gradle wrapper canonical path instead of './gradlew'

---

src/main/java/io/openliberty/tools/intellij/LibertyExplorer.java
src/main/java/io/openliberty/tools/intellij/util/LibertyGradleUtil.java
src/main/java/io/openliberty/tools/intellij/util/LibertyMavenUtil.java

Fixes #182 and #228 
Use name of directory containing the build file if settings.gradle is not found (Gradle) or if artifactId is not found (Maven)

Update Gradle project name

---

build.gradle
src/main/java/io/openliberty/tools/intellij/liberty/lsp/LibertyConfigLanguageServer.java
src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/LanguageServiceAccessor.java
src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/operations/diagnostics/LSPLocalInspectionTool.java

Fixes #258 
- Call `getLanguageServers()` instead of `getLSWrappers()` in `LSPLocalInspectionTool.checkFile()` (inspection/diagnostic logic) to ensure language servers are properly initialized and the correct textDocument/didOpen requests are sent to language servers. 
- Updates org.jetbrains.intellij plugin to 1.12.0
- Add commented out logic to attach JVM debugger to LCLS

Fix for diagnostics not appearing until another LS capability is triggered

---

build.gradle
src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/operations/diagnostics/LSPDiagnosticsToMarkers.java

Part of fix for #85 
After the markers are drawn, forces a refresh of the inspections for the current file to force re-entry of:
https://github.com/OpenLiberty/liberty-tools-intellij/blob/addd86eb8e1da6146dc31cc2a9291fabad61bcff/src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/operations/diagnostics/LSPLocalInspectionTool.java#L63
A better enhancement would be only refresh inspections drawn by LSPLocalInspectionTool, but cannot figure out how to do that programatically currently.

Force refresh of inspections after LS diagnostic markers are drawn

---

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/cdi/ManagedBeanConstructorQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/JakartaCodeActionHandler.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/ModifyAnnotationProposal.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/NewAnnotationProposal.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/InsertAnnotationMissingQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/InsertAnnotationQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/websocket/AddPathParamQuickFix.java

This quick fix enables the addition of the @Inject annotation on a constructor as demonstrated in the test case: jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/cdi/ManagedBeanConstructor.java
This code assumes IntelliJ will add the import statement as part of reformatting. I believe this dependency is also part of the MicroProfile quick fixes. 
Also assuming we do not update the copyright if there were no changes other than the package name. Feel free to comment.

Add ManagedBeanConstructorQuickFix.

---

src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/LSPIJUtils.java

The `toOffset` method would get out of bounds because the it was using the line numbers from the new text, but trying to calculate using the pre-change document.
Added a try/catch to use the end offset of the original document instead.
Fixes some of the quickfixes in #122 
- HealthAnnotationMissingQuickFix
- InsertAnnotationMissingQuickFix
- MicroProfileGenerateOpenAPIOperation
- ApplicationScopedAnnotationMissingQuickFix

Try/catch out of bounds when applying text edits.

---

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/cdi/RemoveInvalidInjectParamAnnotationQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/JakartaCodeActionHandler.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/RemoveAnnotationsProposal.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/RemoveModifierConflictQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/RemoveParamAnnotationQuickFix.java

Resolves #314.
I've been using: https://github.com/eclipse/lsp4jakarta/blob/main/jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/cdi/InjectAndDisposesObservesObservesAsync.java to test these changes. Looks like there's a scaling issue with Jakarta when there a lot of code actions being produced. Only seeing the quick fixes in IntelliJ when the test case is reduced to one or a few methods.

Adding a quick fix for removing annotations from method parameters.

---

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/annotations/PostConstructReturnTypeQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/JakartaCodeActionHandler.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/ModifyReturnTypeProposal.java

Note that this quick fix changes the return type of the method but it does not try to rewrite all the `return` statements.
Fixes #316

Add a quick fix for the @PostConstruct annotation

---

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/beanvalidation/BeanValidationQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/cdi/ManagedBeanNoArgConstructorQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/JakartaCodeActionHandler.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/AddConstructorProposal.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/ModifyModifiersProposal.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/RemoveAnnotationsProposal.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/RemoveModifierConflictQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/RemoveParamAnnotationQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/jax_rs/NoResourcePublicConstructorQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/jax_rs/NonPublicResourceMethodQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/persistence/PersistenceEntityQuickFix.java

Resolves #312 
This PR also updates `AddConstructorProposal`, `ModifyModifiersProposal` and `RemoveAnnotationsProposal` as well existing quick fixes that use these `ChangeCorrectionProposal`s to provide the correct source document to the `Change` object. This addresses an issue with computing the range of text to replace. Will need to apply something similar to the rest of the quick fixes / change proposals.

Adding 3 quick fixes related to ModifyModifiersProposal

---

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/cdi/ScopeDeclarationQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/JakartaCodeActionHandler.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/DeleteAnnotationProposal.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/RemoveAnnotationConflictQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/RemoveMultipleAnnotations.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/jsonb/JsonbTransientAnnotationQuickFix.java

I had to decide between using the new RemoveAnnotationsProposal and porting over the existing DeleteAnnotationProposal and I decided that the loop to find the annotation model objects to pass to the former was just about as difficult as porting the latter. Let me know what you think. 
Not finished with #310 yet.

Quick fixes related to RemoveAnnotationConflictQuickFix

---

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/annotations/RemovePostConstructAnnotationQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/annotations/RemovePreDestroyAnnotationQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/cdi/ConflictProducesInjectQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/cdi/RemoveProduceAnnotationQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/JakartaCodeActionHandler.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/RemoveInjectAnnotationQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/ConflictInjectMultipleConstructorQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/jsonb/JsonbAnnotationQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/persistence/DeleteConflictMapKeyQuickFix.java

Mostly one liners that leverage previous work.

Add quick fixes which simply extend RemoveAnnotationConflictQuickFix.

---

src/main/java/io/openliberty/tools/intellij/actions/LibertyDevStartAction.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyDevStartContainerAction.java
src/main/java/io/openliberty/tools/intellij/actions/ViewIntegrationTestReport.java
src/main/java/io/openliberty/tools/intellij/actions/ViewTestReport.java
src/main/java/io/openliberty/tools/intellij/actions/ViewUnitTestReport.java
src/main/java/io/openliberty/tools/intellij/liberty/lsp/ServerEnvFileType.java
src/main/java/io/openliberty/tools/intellij/liberty/lsp/ServerEnvSubstitutor.java
src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/LanguageServersRegistry.java
src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/LanguageServiceAccessor.java
src/main/java/io/openliberty/tools/intellij/util/LibertyGradleUtil.java
src/main/java/io/openliberty/tools/intellij/util/LibertyMavenUtil.java
src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java

Fixes #239 
Using IntelliJ's VFS `getCanonicalPath()` method can result in `null` return values and lead to NPE's. The main difference between the VFS `getCanonicalPath()` and `getPath()` is that `getCanonicalPath()` will attempt to resolve any symbolic links present in the path. Testing out various scenarios where `getCanonicalPath()` was previously used, it is not necessary to resolve the symlinks, and therefore no need to call `getCanonicalPath()` over `getPath()`.
The IntelliJ quick doc on `getCanonicalPath()` states:
```
Resolves all symbolic links containing in a path to this file and returns a path to a link target (in platform-independent format).
Note: please use this method judiciously. In most cases VFS clients don't need to resolve links in paths and should work with those …
```

239 Replace getCanonicalPath with getPath

---

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/annotations/PostConstructReturnTypeQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/JakartaCodeActionHandler.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/DeleteAnnotationProposal.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/ModifyAnnotationProposal.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/ModifyReturnTypeProposal.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/InsertAnnotationQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/RemoveAnnotationConflictQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/persistence/PersistenceAnnotationQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/CompleteFilterAnnotationQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/CompleteServletAnnotationQuickFix.java

Bring the source compilation unit into the code actions and use to create correct change objects. (Some of these were already done.) Create a sufficient number of copies of the code action context such that each call to getCodeActions() gets a fresh copy of the context. This is necessary to create correct text change proposals.
Fixes #310

Clean up the creation of code actions

---

src/test/java/io/openliberty/tools/intellij/it/SingleModLibertyLSTestCommon.java
src/test/java/io/openliberty/tools/intellij/it/TestUtils.java
src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java
src/test/java/io/openliberty/tools/intellij/it/fixtures/ProjectFrameFixture.java

adds a test that does the following:
- inserts a config stanza to server.xml containing an incorrect attribute value
- hovers on the flagged value and tests the resulting diagnostic popup contents
- opens the quickfix menu and chooses a correct value from list to correct the value in the stanza
- tests the correctness of the fixed stanza

Quickfixtest

---

src/main/java/io/openliberty/tools/intellij/actions/RunLibertyDevTask.java

Fixes https://github.com/OpenLiberty/liberty-tools-intellij/issues/223
The `update()` method is called often, so when the `project` is `null`, we can just return and let successive calls handle setting the action/play button.

Handle null projects when updating Liberty Tool Window project tree

---

src/test/java/io/openliberty/tools/intellij/it/GradleSingleModMPProjectTest.java
src/test/java/io/openliberty/tools/intellij/it/GradleSingleModNLTRestProjectTest.java
src/test/java/io/openliberty/tools/intellij/it/MavenSingleModMPProjectTest.java
src/test/java/io/openliberty/tools/intellij/it/MavenSingleModNLTRestProjectTest.java
src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java
src/test/java/io/openliberty/tools/intellij/it/SingleModNLTRestProjectTestCommon.java
src/test/java/io/openliberty/tools/intellij/it/TestUtils.java
src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java
src/test/resources/files/smNLTRestProject/gradle/build.gradle
src/test/resources/files/smNLTRestProject/gradle/pluginsDSLOnlyDepDef.build.gradle
src/test/resources/files/smNLTRestProject/gradle/server.xml
src/test/resources/files/smNLTRestProject/maven/pom.xml
src/test/resources/files/smNLTRestProject/maven/server.xml

This PR tests:
- The refresh icon on the Liberty tool window toolbar.
- Manually adding to the Liberty tool window a Gradle/Maven app with valid serve.xml and no LGP/LMP config in build file.
- Manually adding to the Liberty tool window a Gradle/Maven app with a valid LMP/LGP config in build file and not a valid server.xml.
- Liberty tools being able to handle a build.gradle build file that defines the plugins DSL to apply the Liberty Tools binary dependency directly from the gradle plugin community.

Add manual refresh tests

---

src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/project/AbstractConfigSource.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/project/PropertiesConfigSource.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/project/PsiMicroProfileProject.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/project/PsiMicroProfileProjectManager.java

Required to address #328.
This PR also fixes several NPEs that could occur if cache eviction overlaps with other operations on the PsiMicroProfileProject. The way PsiMicroProfileProject was written probably still isn't thread-safe, but this addresses the more obvious race conditions.

Listen to in-memory document updates to make the cache more responsive to config changes.

---

src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/LSPIJUtils.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/utils/PsiTypeUtils.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/core/ls/PsiUtilsLSImpl.java

The error return when a module has no source directories should not happen in our case so a harmless non-null value is returned.
Part of #61

Remove use of internal API Module.getModuleFilePath().

---

src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java

fixes #374 
fix intermittent failure on the diagnostic - quickfix testcase by clicking on the editor pane if an attempt fails

when hover does not provoke a popup, click on pane before trying again

---

src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/LanguageServerWrapper.java

The danger in a simple null check is that we will miss or ignore a register capabilities message that will be needed later. I tried several approaches to marshal the threads but they all led to failures elsewhere.
In lsp4e the initializeFuture is not even checked but in IntelliJ this results in the capabilities field not being ready to receive the data (it is null when we need to register something). 
The future is set to null early in the stop() method so I tried to set it later but stopping the language server is performed asynchronously so this did not help. I tried to synchronize with the thread that stops the language server by waiting for it to complete before setting the initialize future to null but this caused a different failure. The language server is stopped asynchronously for …

Check the initialize future for null before using it.

---

.gitignore
src/main/java/io/openliberty/tools/intellij/util/LibertyGradleUtil.java
src/test/java/io/openliberty/tools/intellij/it/GradleSingleModNLTRestProjectTest.java

Addresses #299 and #26
Includes:  
- Minor syntax changes
- Added main regex for identifying the Liberty Gradle plugin. Uses `build.gradle` syntax as heuristics
- Included in the regex is search for optional version definition. 
- Assumes if version is not defined, Gradle pulls the latest version

expand parser on build.gradle

---

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/cdi/ManagedBeanNoArgConstructorQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/RemoveAnnotationConflictQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/persistence/PersistenceEntityQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/FilterImplementationQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/HttpServletQuickFix.java

This mirrors a fix in lsp4jakarta. In very short methods I changed the return to Collections.emptylist() but in the slightly longer methods I moved the definition of the return value out of the `if`. This is more like what we do in lsp4jakarta JDT component.

Ensure getCodeActions() does not return null and returns a list instead.

---

src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/ConnectDocumentToLanguageServerSetupParticipant.java
src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/LanguageClientImpl.java
src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/LanguageServerWrapper.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/core/ls/PsiUtilsLSImpl.java

Address #400 
A specific section pulled from Angelo's https://github.com/redhat-developer/intellij-quarkus/pull/849
The issue with the original fileClosed is that it loops over language servers and tries call getServerCapabilities. When the LS wrapper is stopped and a file is closed, it creates a contradiction to restart the LS with getServerCapabilities and stop at the same time.

Disconnect LS on FileClosed

---

src/main/java/io/openliberty/tools/intellij/liberty/lsp/LibertyConfigLanguageServer.java
src/main/java/io/openliberty/tools/intellij/liberty/lsp/LibertyXmlServer.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp/JakartaLanguageServer.java
src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp/MicroProfileServer.java
src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/server/ProcessStreamConnectionProvider.java
src/main/java/io/openliberty/tools/intellij/util/Constants.java

Resolves #196.
Used the VS Code tools as a reference for this fix. See the `checkJavaVersion()` and `parseMajorVersion()` functions in: https://github.com/OpenLiberty/liberty-tools-vscode/blob/main/src/util/requirements.ts.

Report an error if Java 17 (or higher) is not found for launching the language servers.

---

src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/DocumentContentSynchronizer.java

Temp fix to make #441 less severe
Check to see if the project associated with the languageServerWrapper object is disposed before trying to get a PsiDocumentManager instance.

441 quick patch

---

.github/workflows/build.yaml
build.gradle
src/test/java/io/openliberty/tools/intellij/it/GradleSingleModMPProjectTest.java
src/test/java/io/openliberty/tools/intellij/it/MavenSingleModMPProjectTest.java
src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java
src/test/resources/files/smNLTRestProject/gradle/server.xml
src/test/resources/projects/gradle/sampleGradleMPLSApp/build.gradle
src/test/resources/projects/gradle/singleModGradleMP/build.gradle
src/test/resources/projects/gradle/singleModGradleRESTNoLTXmlCfg/build.gradle
src/test/resources/projects/gradle/singleModGradleRESTNoLTXmlCfg/src/main/liberty/config/myLibertyConfig.xml

Result from skills transfer prep.
This PR:
- Enables container tests for Gradle test runs.
- Standardizes the use of default ports in the Gradle test projects (required to enable container tests).
- Cleanup unnecessary code/config.

Enable container tests for Gradle test runs

---

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/PropertiesManagerForJakarta.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/jax_rs/NonPublicResourceMethodQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/PropertiesManagerForJava.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/core/java/codeaction/CodeActionHandler.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/core/java/codeaction/JavaCodeActionDefinition.java
src/main/resources/META-INF/plugin.xml

This is a starting point for merging MP and Jakarta EE on to one design for code actions. I only transformed one Jakarta EE quick fix to provide an example. A similar pattern can be applied for transforming the rest of them. We should enable the automated tests for Jakarta EE code actions: https://github.com/OpenLiberty/liberty-tools-intellij/issues/476 as we complete this work.

Proof-of-concept for unifying the design for MicroProfile and Jakarta EE code actions.

---

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/ExtendClassProposal.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/HttpServletQuickFix.java

Resolves #520. See the detailed description of the problem on this issue.

Resolve functional issues with ExtendClassProposal.

---

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/JakartaCodeActionHandler.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/ModifyModifiersProposal.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/RemoveAbstractModifierQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/RemoveFinalModifierQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/RemoveModifierConflictQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/RemoveStaticModifierQuickFix.java
src/main/resources/META-INF/plugin.xml
src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/di/DependencyInjectionTest.java

Fixes #522
Refactored RemoveModifierQuickFix and bring the test cases ready
Bring the quick fix working for RemoveStaticModifierQuickFix, RemoveAbstractModifierQuickFix and RemoveFinalModifierQuickFix

Fixes #522: Refactored RemoveModifierQuickFix and bring the test cases ready

---

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/AbstractDiagnosticsCollector.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/PropertiesManagerForJakarta.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/PropertiesManagerForJava.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/java/diagnostics/DiagnosticsHandler.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/java/diagnostics/IJavaDiagnosticsParticipant.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/core/java/corrections/JavaDiagnosticsDefinition.java
src/main/resources/META-INF/plugin.xml

Resolves #501.
1. Transformed `AbstractDiagnosticsCollector` so that it implements `IJavaDiagnosticsParticipant`. This is the base class for all of the Jakarta EE diagnostic collectors.
2. Created `JavaDiagnosticsDefinition`, a bean wrapper class around `IJavaDiagnosticsParticipant` which includes a group field to distinguish between diagnostics for different language servers (e.g. MP vs. Jakarta EE).
3. Refactored diagnostics related code from the MP `PropertiesManagerForJava` into its own class: `DiagnosticsHandler`, enhancing this code to use the group field when filtering the list of diagnostics collectors.
4. Plugged the `DiagnosticsHandler` into the `PropertiesManagerForJakarta`, replacing the diagnostics related code from this class.
5. Changed the definition of the …

Transform the Jakarta EE diagnostic collectors on to a common extension point shared with MicroProfile.

---

build.gradle
src/main/java/io/openliberty/tools/intellij/liberty/lsp/LibertyConfigLanguageClient.java
src/main/java/io/openliberty/tools/intellij/liberty/lsp/LibertyCustomConfigListener.java
src/main/java/io/openliberty/tools/intellij/liberty/lsp/LibertyCustomConfigManager.java
src/main/java/io/openliberty/tools/intellij/liberty/lsp/ServerEnvFileType.java
src/main/java/io/openliberty/tools/intellij/liberty/lsp/ServerEnvSubstitutor.java
src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/LanguageClientImpl.java
src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/LanguageServerWrapper.java
src/main/java/io/openliberty/tools/intellij/util/Constants.java
src/main/resources/META-INF/lsp.xml
src/test/resources/ci/scripts/run.sh

Resolves #490 
Add file listener - notify LCLS to process `liberty-plugin-config.xml` files when a filechange is detected.
Also requires LCLS 2.1 or 2.1-SNAPSHOT
Merging this change does not break existing support for LCLS files.
Currently this only works if `liberty-plugin-config.xml` changes _**after**_ IntelliJ/LCLS is initialized. 
Liberty Tools IntelliJ doesn't initialize workspace folders, which is how the custom config files are discovered on LCLS initialization. Related to #483
**Also to note**, it seems the intellij-quarkus plugin has made changes to enable workspace folders, and also enable the LSP protocol for `workspace/didChangeWatchedFiles`, which may replace these changes at some point in the future.

Add filewatcher to enable custom config support for LCLS

---

src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunConfiguration.java
src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunSettingsEditor.form
src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunSettingsEditor.java
src/main/resources/META-INF/plugin.xml

Fixes #160 
Added checkbox in run/debug config window.
When the checkbox is selected, will run liberty:devc/libertyDevc when starting dev mode.

Fixes #160 'Run in container' checkbox option in Run/Debug Config

---

build.gradle
src/main/resources/META-INF/plugin.xml

Fixes #487 
- Update to support IDEA version 2023.2 and its subsequent fix releases
- Update development and test IDEA version to 2023.2.3
- Update `maven-test-framework` to version 232.10072.27
NOTE: Tests under `lsp4jakarta.it` have been disabled due to a listener leak error introduced with the 232 version of the maven-test-framework - issue for that here: #541. The `main-clone-oct-21` branch was created to preserve a version of `main` where the `lsp4jakarta.it` tests still run.

Update to support IDEA version 2023.2.*

---

build.gradle
src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/core/BaseJakartaTest.java

Fixes #541 
Fixed Listener leak error with 232 version of maven-test-framework.
Enabled integration tests.

Fixed Listener leak error with 232 version of maven-test-framework

---

src/main/java/io/openliberty/tools/intellij/actions/LibertyDevStartContainerAction.java

Fixes #550 Added custom parameter in start in container

Fixes #550 Added custom parameters in start container

---

src/main/java/io/openliberty/tools/intellij/LibertyExplorer.java

Fixes #561 
Hopefully by avoiding the ClassCastException the IntelliJ framework can continue to render projects and it will not allow the project to disappear and reappear in the projects view. I was not able to reproduce the project disappear/reappear bug,

Check if an object is a LibertyModuleNode before trying to cast it.

---

src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java

Disables tests that were affected by PR 553 while we continue searching for a solution to #564.

Disable Linux tests for running dev mode in a container that were impacted by PR 553.

---

src/main/java/io/openliberty/tools/intellij/util/LibertyMavenUtil.java

Adding required null checks for return values from methods marked as @Nullable.

---

src/main/java/io/openliberty/tools/intellij/actions/LibertyDevStartAction.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyDevStartContainerAction.java
src/main/java/io/openliberty/tools/intellij/util/LibertyMavenUtil.java

Fixes #563
~Also, if the maven wrapper near the build file fails the checks, try to use the maven wrapper at the project level.~

Assume the maven wrapper is in the directory with the build file pom.xml

---

.github/workflows/build.yaml
build.gradle
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp/JakartaLanguageClient.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/JakartaProjectLabelProvider.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/PropertiesManagerForJakarta.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/PropertiesManagerForJava.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/java/completion/CompletionHandler.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/java/completion/IJavaCompletionParticipant.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/java/diagnostics/DiagnosticsHandler.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/java/diagnostics/IJavaDiagnosticsParticipant.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/core/java/codeaction/CodeActionHandler.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/core/java/completion/JavaCompletionDefinition.java
src/main/resources/META-INF/plugin.xml
src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/annotations/GeneratedAnnotationTest.java
src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/annotations/PostConstructAnnotationTest.java
src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/annotations/PreDestroyAnnotationTest.java
src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/annotations/ResourceAnnotationTest.java
src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/beanvalidation/BeanValidationTest.java
src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/cdi/ManagedBeanConstructorTest.java
src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/cdi/ManagedBeanTest.java
src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/core/JakartaForJavaAssert.java
src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/di/DependencyInjectionTest.java
src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/di/MultipleConstructorInjectTest.java
src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/jaxrs/ResourceClassConstructorTest.java
src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/jaxrs/ResourceMethodTest.java
src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/jsonb/JsonbDiagnosticsCollectorTest.java
src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/jsonp/JakartaJsonpTest.java
src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/persistence/JakartaPersistenceTest.java
src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/servlet/JakartaServletTest.java
src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/websocket/JakartaWebSocketTest.java

This PR addresses: https://github.com/OpenLiberty/liberty-tools-intellij/issues/521 by upgrading to [LSP4Jakarta 0.2.0](https://github.com/eclipse/lsp4jakarta/releases/tag/0.2.0) and updating our implementation of the client to align with the changes that were made to the client API in this new version of LSP4Jakarta.
Notable changes in this PR:
- Updated the `JakartaLanguageClient` to support the LSP4Jakarta 0.2.0 client API and all of its messages.
- Supported resolveCodeAction() as a separate message. LSP4Jakarta 0.2.0 does not call this method but the wiring is in place to work with a future version of LSP4Jakarta.
- Supported new messages for project labels and file info. The code is shared with the MP client. Introduced a label provider for Jakarta projects (see …

Upgrade to LSP4Jakarta 0.2.0. Unify MP / Jakarta EE completion support.

---

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/RemoveElementsProposal.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/RemoveParamsProposal.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/RemoveMethodParametersQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/jax_rs/ResourceMethodMultipleEntityParamsQuickFix.java
src/main/resources/META-INF/plugin.xml
src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/annotations/PostConstructAnnotationTest.java
src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/annotations/PreDestroyAnnotationTest.java
src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/jaxrs/ResourceMethodTest.java

Fixes #534 
Refactored quick fixes and test cases for RemoveParamsProposal

Fixes #534: Refactored quick fixes and test cases for RemoveParamsProposal

---

.github/workflows/build.yaml

The build.yaml on main currently pulls lsp4ij from the Microshed branch main. Now that new code has been merged into main we need to pull from the correct lsp4ij tag, 0.0.1. 
This should be our practice going forward, make a tag in lsp4ij and pull the tag into this build.

Specify the correct tag for lsp4ij.

---

.github/workflows/build.yaml
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/core/java/completion/JavaCompletionDefinition.java

Added a catch/rethrow of IndexNotReadyException, ProcessCanceledException, CancellationException to the wrapper methods of `JavaCompletionDefinition`. Resolves https://github.com/OpenLiberty/liberty-tools-intellij/issues/634.

Adding a catch and rethrow for exceptions that should be propagated up the call stack.

---

.github/workflows/build.yaml

Resolves https://github.com/OpenLiberty/liberty-tools-intellij/issues/628.

Enable GitHub action to be triggered manually.

---

build.gradle
src/main/java/io/openliberty/tools/intellij/LibertyExplorer.java
src/main/java/io/openliberty/tools/intellij/util/LibertyMavenUtil.java
src/main/resources/META-INF/plugin.xml
src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java
src/test/resources/ci/scripts/run.sh

Pull in Vaisakh's changes.
One change, remove the code that runs LibertyExplorer on a background thread because it caused an exception involving the need to run the code on the event thread. Also when running the tests use an option not to generate an assertion (red warning dialog) when the slow operation on event thread exception is generated.

Use IntelilJ 2023.3

---

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/PropertiesManagerForJakarta.java

Resolves https://github.com/OpenLiberty/liberty-tools-intellij/issues/681. This is achieved by treating `JavaCursorContextKind.NONE` as a special case, avoiding the issue with retrieving the enum value through the `forValue()` method.

Implementing a workaround for an issue with JavaCursorContextKind.forValue().

---

src/main/resources/META-INF/plugin.xml

Did a quick smoke test on IntelliJ IDEA 2023.2 and 2023.3.6

Bump minimum supported IDE version to 2023.2

---

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/cdi/ManagedBeanDiagnosticsCollector.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/cdi/ScopeDeclarationQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/jsonb/JsonbDiagnosticsCollector.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/jsonb/JsonbTransientAnnotationQuickFix.java
src/main/resources/META-INF/plugin.xml
src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/cdi/ManagedBeanTest.java
src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/jsonb/JsonbDiagnosticsCollectorTest.java

Fixes #611
LSP4Jakarta ambiguously matches the expected class names when checking diagnostics, applying quick fixes, etc
Updated all of the diagnostic collectors to include fully qualified class names in the diagnostic data that they produce. And fixed the quick fix  issue of JsonbTransientAnnotationQuickFix and ScopeDeclarationQuickFix.

Fixes #611 LSP4Jakarta ambiguously matches the expected class names when checking diagnostics, applying quick fixes, etc

---

src/test/java/io/openliberty/tools/intellij/it/TestUtils.java

Fixes #707 
I confirmed that each of the tests relying on the method **validateTestReportExists** (https://github.com/OpenLiberty/liberty-tools-intellij/blob/main/src/test/java/io/openliberty/tools/intellij/it/TestUtils.java#L377)  failed when a test report was not created.

Fixed to throw IllegalStateException

---

src/main/java/io/openliberty/tools/intellij/actions/LibertyGeneralAction.java
src/main/java/io/openliberty/tools/intellij/actions/RefreshLibertyToolbar.java
src/main/java/io/openliberty/tools/intellij/actions/RunLibertyDevTask.java

Resolves https://github.com/OpenLiberty/liberty-tools-intellij/issues/720. Schedule Liberty actions to run on the `EDT`. This is effectively the same as the default `OLD_EDT` which is deprecated.

Override AnAction.getActionUpdateThread() as required by IntelliJ.

---

src/main/resources/META-INF/plugin.xml

Fixes #699 
You can test with a project created at microprofile.io that includes graphql (check the appropriate box).
One diagnostic is generated when you add @Query to a field in a class.

Add GraphQL support for diagnostics for MicroProfile

---

src/main/java/io/openliberty/tools/intellij/actions/LibertyDevRunTestsAction.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyDevStartAction.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyDevStartContainerAction.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyDevStopAction.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyGeneralAction.java
src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java

Fixes #198 -->  Added code to make sure the focus shifts correctly for each terminal when we perform dev-actions, also tested that terminal renaming works properly.
We can close these dependent issues #505, #506, once the PR is merged.

Fixes #198 -- Add code to shift focus correctly for each terminal

---

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/annotations/PostConstructReturnTypeQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/beanvalidation/BeanValidationQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/cdi/ManagedBeanNoArgConstructorQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/cdi/ManagedBeanQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/InsertAnnotationMissingQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/InsertAnnotationQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/RemoveAnnotationConflictQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/RemoveMethodParametersQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/RemoveModifierConflictQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/RemoveParamAnnotationQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/jax_rs/NoResourcePublicConstructorQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/jax_rs/NonPublicResourceMethodQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/jax_rs/ResourceMethodMultipleEntityParamsQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/persistence/PersistenceAnnotationQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/persistence/PersistenceEntityQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/CompleteFilterAnnotationQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/CompleteServletAnnotationQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/FilterImplementationQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/HttpServletQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/ListenerImplementationQuickFix.java

Added a catch/rethrow of IndexNotReadyException, ProcessCanceledException, CancellationException to `resolveCodeAction()` and related methods. Resolves https://github.com/OpenLiberty/liberty-tools-intellij/issues/635.
Also cleaned up imports and updated copyrights.

Jakarta EE quick fixes: Adding a catch and rethrow for exceptions that should be propagated up the call stack.

---

src/main/resources/META-INF/plugin.xml
src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/cdi/ManagedBeanConstructorTest.java

Resolves https://github.com/OpenLiberty/liberty-tools-intellij/issues/763 by including the missing quick fix and completing enablement of the relevant unit test.

Include ManagedBeanConstructorQuickFix and update unit tests.

---

src/test/java/io/openliberty/tools/intellij/it/SingleModJakartaLSTestCommon.java
src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java

Three green builds in a row. Hopefully not due to luck.
Just to explain the fix, when the robot pastes the search text into the search box in the following screen the robot pauses 1s before reading and searching the options underneath. Likely the options are generated asynchronously on a separate thread. 
Fixes #768
Fixes #769

Wait for list of options to be populated.

---

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/beanvalidation/BeanValidationConstants.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/beanvalidation/BeanValidationDiagnosticsCollector.java
src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/beanvalidation/BeanValidationTest.java

Fixes #781
I just enabled the test for diagnostics (d18) and added a test for the corresponding quick fix.

Fix  Diagnostic missing for @PositiveOrZero and enabled test

---

.github/workflows/build.yaml
build.gradle

Build lsp4ij plugin from main branch to use in the LTI automated tests - Issue#758

---

src/main/java/io/openliberty/tools/intellij/util/LibertyMavenUtil.java

Fixes #823 
Updated `getMavenHome()` method to `getMavenHomeType()` method and
Updated `resolveMavenHomeDirectory()` method to `getMavenHomeFile()` method

Fixed using Deprecated Maven Methods which are Marked for Removal

---

.github/workflows/build.yaml
.github/workflows/cronJob.yaml
build.gradle
src/test/resources/ci/scripts/run.sh

Part of #666 
- Fixes #758 - Build lsp4ij plugin from a branch to use in the LTI automated tests
Checkout any branch of `lsp4ij` (main or any merge commit SHA) and use the `buildPlugin` command to create a ZIP file from it. Unzip the file and specify the path to the `lib` folder as a plugin dependency in `build.gradle`.
- Fixes #756 - Set up a cron job to run every midnight
Created a new YAML file named `cronJob.yaml` with the `useLocalPlugin` value set to `true`. This configuration ensures that the cron job will execute the LTI build with `useLocalPlugin=true`.
- Fixes #783 -  Parameterize LTI Build.
Build and run tests using lsp4ij either (1) from the marketplace or (2) locally. Added a `workflow_dispatch` event so that we can check the `useLocalPlugin` as true or false. 
- Fixes #757 - …

Continuous integration of the Red Hat LSP4iJ plug-in

---

.github/workflows/cronJob.yaml

Run builds for those PRs which do not contain a merge conflict - Issue #845

---

.github/workflows/build.yaml

Fixes #866 . Updated the upload-artifact version and also changed the file name of the artifact

Rename Artifact file and upgrade actions/upload-artifact version

---

src/main/java/io/openliberty/tools/intellij/actions/LibertyGeneralAction.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/annotations/AnnotationDiagnosticsCollector.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/annotations/PostConstructReturnTypeQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/beanvalidation/BeanValidationDiagnosticsCollector.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/utils/PsiTypeUtils.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/graphql/java/MicroProfileGraphQLASTValidator.java
src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java

Fixes #846 
There are 20 usages of scheduled for removal API.
- Scheduled for removal fields usages (11)
- Scheduled for removal classes usages (4)
- Scheduled for removal methods usages (4)
- Scheduled for removal enum usage (1)

Fixes issue 846 - usage of APIs scheduled for removal #855

---

build.gradle

Need also to reorganize the order of some lines to group them logically.
Also fixes the same issue in ManagedBeanDiagnosticsCollector.
Fixes #858

Exclude gson from dependencies so we use the one from LSP4IJ

---

.github/workflows/build.yaml
.github/workflows/cronJob.yaml

Fixes - Part of #868 
The Artifacts will look like:

Enhance artifact name #868

---

src/main/java/io/openliberty/tools/intellij/LibertyExplorer.java
src/main/java/io/openliberty/tools/intellij/LibertyModule.java
src/main/java/io/openliberty/tools/intellij/LibertyModuleNode.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyProjectAction.java
src/main/java/io/openliberty/tools/intellij/util/BuildFile.java
src/main/java/io/openliberty/tools/intellij/util/LibertyGradleUtil.java
src/main/java/io/openliberty/tools/intellij/util/LibertyMavenUtil.java
src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java

part of #847 
Replaced Psi file with Virtual file. Because intellij deprecated FilenameIndex.getFilesByName(...) method and instead of this method they suggested to use FilenameIndex.getVirtualFilesByName(). The 'getFilesByName' method was returning array of PsiFile objects, the new method 'getVirtualFilesByName' is returning Collection<VirtualFile>. So replaced 'PsiFile' object with 'VirtualFile'.

Deprecated the method FilenameIndex.getFilesByName() 

---

.github/workflows/pr-slack-notification.yaml

Fixes #848 
I created a new `Slack Workflow Builder(No LSP4IJ PRs)` for sending messages to a Slack channel when there are **no new, closed, or updated PRs** to list(Option 2 that mentioned in issue #848) . I added the new webhook URL from Slack Workflow Builder as a secret in my forked Intellij repository.

Use different Slack workflow builder message when there are no new/Updated/Closed PRs

---

src/test/java/io/openliberty/tools/intellij/it/GradleSingleModJakartaLSTest.java
src/test/java/io/openliberty/tools/intellij/it/GradleSingleModLSTest.java
src/test/java/io/openliberty/tools/intellij/it/GradleSingleModMPLSTest.java

Fixes #655 . Removed @DisabledOnOs({OS.WINDOWS}) 
Observations - https://github.com/OpenLiberty/liberty-tools-intellij/issues/655#issuecomment-2247569020

Enabled UI Tests in Windows 

---

src/main/java/io/openliberty/tools/intellij/util/LibertyActionUtil.java

Part of #847 
1. getTerminalStarter() replaced with getTerminal()
2. used getCodeForKey() method to add new line character after command

issue 847 Replaced deprecated methods in jediTermWidget class

---

src/main/java/io/openliberty/tools/intellij/actions/LibertyGeneralAction.java
src/main/java/io/openliberty/tools/intellij/actions/ViewIntegrationTestReport.java
src/main/java/io/openliberty/tools/intellij/actions/ViewTestReport.java
src/main/java/io/openliberty/tools/intellij/actions/ViewUnitTestReport.java
src/main/java/io/openliberty/tools/intellij/lsp4mp/MicroProfileDeploymentSupport.java
src/main/java/io/openliberty/tools/intellij/lsp4mp/MicroProfileProjectService.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/classpath/ClasspathResourceChangedManager.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/PropertiesManagerForJava.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/java/completion/CompletionHandler.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/java/diagnostics/DiagnosticsHandler.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/project/PsiMicroProfileProjectManager.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/core/java/codeaction/CodeActionHandler.java
src/main/java/io/openliberty/tools/intellij/util/JavaVersionUtil.java

Part of #847 
1. Replaced 'ExtensionPointName.extensions()' with 'getExtensionList().stream()
2. Replaced ServiceManager.getService with project.getService.
3. Replaced deprecated field ProjectTopics.MODULES with ModuleListener.TOPICS.
4. Updated deprecated Notification constructor and removed deprecated setListener method.

Issue 847 deprecated api usage 

---

.github/workflows/build.yaml
.github/workflows/cronJob.yaml

Fixes #759 
I have added code for sending LSP4IJ integration build results to Slack channel. Currently I am using the same channel `lsp4ij-monitoring` and using the same secret variable `SLACK_WEBHOOK_URL`
I have tested with the changes in the PR https://github.com/OpenLiberty/liberty-tools-intellij/pull/864 which is opened against the issue #815

Fix sending LSP4IJ integration build results to Slack channel

---

src/main/java/io/openliberty/tools/intellij/util/LibertyMavenUtil.java

Resolves https://github.com/OpenLiberty/liberty-tools-intellij/issues/904.
This PR configures the `DocumentBuilderFactory` used by `LibertyMavenUtil` to block well known denial-of-service attacks. Directly creates an instance of the system-default implementation to prevent an override from a potentially untrusted JAXP implementation.

Set the secure processing feature on an instance of the system-default DocumentBuilderFactory.

---

src/main/java/io/openliberty/tools/intellij/actions/ViewTestReport.java

Resolves https://github.com/OpenLiberty/liberty-tools-intellij/issues/905.

Write exceptions to the logger instead of directly printing their stack trace to the console.

---

.github/workflows/build.yaml
.github/workflows/cronJob.yaml

Fixes #815 
A part of the fix for - [#868](https://github.com/OpenLiberty/liberty-tools-intellij/issues/868)
Implementation of running LSP4iJ continuous integration builds with existing LTI releases
Currently, the fix is running against the branch `lsp4ij-market-0.0.2-integration`. We can add the `main` and other existing `LTI release tags`, but those will fail because of the `microshed:lsp4ij` dependency. Once we have an LTI release that uses the `redhat:lsp4ij` plugin, we will be able to easily add the version in the `tag` specified in the code.

Fix running LSP4iJ continuous integration builds with existing LTI releases

---

.github/workflows/build.yaml
.github/workflows/cronJob.yaml

Fixes #856 
I have updated the versions of `Checkout Actions` and `Upload Artifacts`. We changed `actions/upload-artifact` to `v4.3.4`, and I have given unique names to the `test reports.` This is necessary because we are running builds for different PRs, different LTI Tags, and the main branch, so we need to uniquely identify the test reports.
I am using the environment variable `env.REF_LTI_TAG` to name the `test reports`. Since the value is currently empty, it defaults to `'default'`. After merging this PR https://github.com/OpenLiberty/liberty-tools-intellij/pull/864, the value will take the exact value of `env.REF_LTI_TAG`. There is no issue with merging this PR first or merging the above-mentioned PR first.
I have added an extra condition to the step `Archive Test logs and reports` …

Fix to Update Versions of Checkout Actions and Upload Artifacts

---

.github/workflows/build.yaml
src/test/resources/ci/scripts/setup.sh

Fixes #902 
Since we are using `macOS-latest`, which refers to `macOS 14 Arm64`,we can check [here](https://github.com/actions/runner-images?tab=readme-ov-file#about)
Upon reviewing the [readme](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md), I found that they are using `macOS version 14.6.1` now, and this update is reflected in the `documentation`. Therefore, we can confirm that they won't revert to `macOS version` 14.5. 
I have suppressed the warning for the command `brew install curl unzip || true` by using the` --quiet` option. 
The `--quiet` option in Homebrew's `brew install` command is used to minimize the output by suppressing some of the usual messages that appear during installation.
I have updated the branch to` …

Fix warnings in Workflows on macOS 14.6 for curl 

---

src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java

Fixes #916
This affects four test cases that have quick fixes.

Add a 5s delay after clicking on a quick fix

---

.github/workflows/build.yaml
build.gradle

Resolves https://github.com/OpenLiberty/liberty-tools-intellij/issues/914.
The upgrade to LSP4MP 0.12.0-SNAPSHOT is required to resolve a problem exposed by the introduction of `workspace/symbols` support in LSP4iJ 0.4.0. See the discussion here for more information: https://github.com/redhat-developer/lsp4ij/discussions/452#discussioncomment-10329922.
IntelliJ 2024.1.6 is now the current 2024.1.x release and we should be using it for our automated testing.

Upgrade to LSP4iJ 0.4.0, IntelliJ 2024.1.6 and LSP4MP 0.12.0-SNAPSHOT.

---

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/RemoveParamAnnotationQuickFix.java

Resolves https://github.com/OpenLiberty/liberty-tools-intellij/issues/924
This addresses an issue that we will immediately encounter when upgrading to LSP4Jakarta 0.2.2. Fixing this now to make the future upgrade go more smoother.

Cast the value to a Number in order to tolerate type conversion from Integer to Double.

---

build.gradle
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/PropertiesManagerForJava.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/java/codelens/IJavaCodeLensParticipant.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/java/completion/CompletionHandler.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/java/completion/IJavaCompletionParticipant.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/java/definition/IJavaDefinitionParticipant.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/java/diagnostics/DiagnosticsHandler.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/java/diagnostics/IJavaDiagnosticsParticipant.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/java/hover/IJavaHoverParticipant.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/java/symbols/IJavaWorkspaceSymbolsParticipant.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/jaxrs/IJaxRsInfoProvider.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/utils/PsiTypeUtils.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/core/java/codeaction/CodeActionHandler.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/graphql/java/MicroProfileGraphQLASTValidator.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/jaxrs/java/DefaultJaxRsInfoProvider.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/jaxrs/java/JaxRsInfoProviderRegistry.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/jaxrs/java/JaxRsWorkspaceSymbolParticipant.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/reactivemessaging/properties/MicroProfileReactiveMessagingProvider.java
src/main/resources/META-INF/plugin.xml

Fixes #841 
- Update lsp4mp4ij component to align with Quarkus Tools for IntelliJ release 2.0.0: https://github.com/redhat-developer/intellij-quarkus/releases/tag/2.0.0
-  Update LSP4MP to 0.12.0: https://github.com/eclipse/lsp4mp/releases/tag/0.12.0

Update lsp4mp4ij component to align with Quarkus Tools for IntelliJ release 2.0.0 & Update LSP4MP to 0.12.0

---

src/main/java/io/openliberty/tools/intellij/LibertyModule.java
src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunManagerListener.java

Fixes #955 - Deletion of configuration does not remove 'Start in Container' Setting when enabled

issue 955 - clear run in container module setting on run config deletion

---

src/main/resources/META-INF/plugin.xml

Due to backwards compatibility issues with the changes to remove deprecated APIs and other deprecated code, moving forward the minimum supported version of IntelliJ will be 2024.1.

Support IntelliJ IDEA 2024.1.* only

---

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/jax_rs/ResourceMethodMultipleEntityParamsQuickFix.java

Resolves https://github.com/OpenLiberty/liberty-tools-intellij/issues/956
This addresses an issue that we will immediately encounter when upgrading to LSP4Jakarta 0.2.2. Fixing this now to make the future upgrade go more smoother.

Casts values to a Number in order to tolerate type conversion from Integer to Double.

---

src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/openapi/java/MicroProfileGenerateOpenAPIOperation.java

In MicroProfileGenerateOpenAPIOperation we call PsiClass.getQualifiedName() which is nullable. It returns null when the class is local or a type parameter. In our test case we used a type parameter so we see the need to check the return type.
Fixes #995

Check for null or empty class name in generate OpenAPI annotations

---

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/AnnotationUtil.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/annotations/PostConstructReturnTypeQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/beanvalidation/BeanValidationQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/cdi/ManagedBeanNoArgConstructorQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/cdi/ManagedBeanQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/InsertAnnotationMissingQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/InsertAnnotationQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/RemoveAnnotationConflictQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/RemoveMethodParametersQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/RemoveModifierConflictQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/RemoveParamAnnotationQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/jax_rs/NoResourcePublicConstructorQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/jax_rs/NonPublicResourceMethodQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/jax_rs/ResourceMethodMultipleEntityParamsQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/persistence/PersistenceAnnotationQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/persistence/PersistenceEntityQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/CompleteFilterAnnotationQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/CompleteServletAnnotationQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/FilterImplementationQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/HttpServletQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/ListenerImplementationQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/java/codeaction/InsertAnnotationAttributeQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/java/codeaction/InsertAnnotationMissingQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/java/validators/annotations/AnnotationValidator.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/core/java/completion/JavaCompletionDefinition.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/core/java/corrections/JavaDiagnosticsDefinition.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/faulttolerance/java/MicroProfileFaultToleranceASTValidator.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/health/java/ImplementHealthCheckQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/metrics/java/ApplicationScopedAnnotationMissingQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/openapi/java/MicroProfileGenerateOpenAPIOperation.java

Fixes #767 
I found many usages of the following 
`catch (IndexNotReadyException | ProcessCanceledException | CancellationException e)`
I have changed the code as suggested by IntelliJ.
I haven't found the exact usage of the following in our code.
`catch (CancellationException | ProcessCanceledException e)`

Fix usage of ProcessCanceledException and CancellationException in catch block

---

.github/workflows/pr-slack-notification.yaml

Fixes #937 
Updated the GitHub `actions` versions to resolve the warnings

Fix for warnings in the pr-slack-notification.yaml Cron Job Builds

---

.github/workflows/cronJob.yaml

Fixes #947
I have created a new `Slack Workflow Builder` to display build results in a Slack channel, allowing us to edit it at any time. We receive values such as the `build status`,` workflow run link`, and the `branch` that triggered the workflow. These values are used in the Slack Workflow Builder, and based on the message configured there, the results are displayed in the Slack channel.
We added an additional secret to the LTI repo for its working

Use Slack Workflow Builder to Trigger Notifications and Enable Editing and Tagging of Developers

---

src/main/resources/messages/LibertyBundles.properties

Fixes #997  corrected Invalid Gradle test param example in hover for start parameters

Fixes 997 : Invalid gradle test param example in hover for start parameters 

---

src/main/resources/META-INF/lsp.xml

Resolves https://github.com/OpenLiberty/liberty-tools-intellij/issues/1007
This will take effect with the release of LSP4IJ 0.7.0.

Set languageId for each of the MicroProfile language mappings.

---

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/cdi/ManagedBeanConstants.java

Resolves https://github.com/OpenLiberty/liberty-tools-intellij/issues/1028

ManagedBeanConstants: Remove unused constants for unqualified class names.

---

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DependencyInjectionConstants.java

Resolves https://github.com/OpenLiberty/liberty-tools-intellij/issues/1029

DependencyInjectionConstants: Remove unused constants for unqualified class names.

---

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/annotations/AnnotationDiagnosticsCollector.java

Resolves https://github.com/OpenLiberty/liberty-tools-intellij/issues/1026

AnnotationDiagnosticsCollector: Use equals() for checking for equality of qualified names.

---

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/beanvalidation/BeanValidationConstants.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/beanvalidation/BeanValidationDiagnosticsCollector.java

Resolves https://github.com/OpenLiberty/liberty-tools-intellij/issues/1027
Also removed unused constants for unqualified class names.

BeanValidationDiagnosticsCollector: Use qualified names and equals() for checking built-in types.

---

src/test/java/io/openliberty/tools/intellij/it/SingleModMPLSTestCommon.java

Currently waits zero so always wait 1s and optionally up to 60s. It appeared after 35s in one case on Mac so this leaves a few extra seconds buffer.
Fixes #1043

Wait up to 60s for Java diagnostic to appear

---

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/persistence/PersistenceMapKeyDiagnosticsCollector.java

Resolves https://github.com/OpenLiberty/liberty-tools-intellij/issues/1024

PersistenceMapKeyDiagnosticsCollector: Move body of the for loops over methods and fields into a common method.

---

src/test/java/io/openliberty/tools/intellij/it/SingleModJakartaLSTestCommon.java
src/test/java/io/openliberty/tools/intellij/it/SingleModLibertyLSTestCommon.java
src/test/java/io/openliberty/tools/intellij/it/SingleModMPLSTestCommon.java
src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java
src/test/java/io/openliberty/tools/intellij/it/SingleModNLTRestProjectTestCommon.java
src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java

First we try to find the window and then if it is closed we click on the button to open it. But if the window does not open right away on a slow machine then the next time we repeat this action we will click a second time and end up closing the window we want open. So add a short delay after we click. Also added is a slightly longer delay before we try to look for the window in case a previous operation is still running. 
I believe one of the exceptions listed in the issue is caused by the problem of the first exception: `Exceeded timeout ... Failed to find 'Welcome Frame' ` 
Fixes #971

Wait after clicking button to open window

---

.github/workflows/build.yaml
build.gradle

Resolves https://github.com/OpenLiberty/liberty-tools-intellij/issues/1059. This PR upgrades to the latest LSP4Jakarta 0.2.2 snapshot. Also includes LSP4MP 0.13.0 which is also included in this PR https://github.com/OpenLiberty/liberty-tools-intellij/pull/1058 for `main`.

Upgrade to LSP4Jakarta 0.2.2.

---

src/main/java/io/openliberty/tools/intellij/util/DebugModeHandler.java
src/test/resources/ci/scripts/run.sh

Fixes #1060
The default value is 3 minutes. This was chosen because Gradle can be slow to start. On github action machines it can take 4-5 minutes to start Liberty dev mode. So we added an environment variable to allow us to specify a longer timeout when testing. The timeout when testing is 8 minutes.

Add environment variable to set the timeout when starting dev mode Liberty for debugging

---

src/test/java/io/openliberty/tools/intellij/it/GradleSingleModMPProjectTest.java
src/test/java/io/openliberty/tools/intellij/it/GradleSingleModMPSIDProjectTest.java
src/test/java/io/openliberty/tools/intellij/it/MavenSingleModMPProjectTest.java
src/test/java/io/openliberty/tools/intellij/it/MavenSingleModMPSIDProjectTest.java
src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java
src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java
src/test/java/io/openliberty/tools/intellij/it/fixtures/ProjectFrameFixture.java

Stop the running terminal and then Clean and close all terminal tabs.

---

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/websocket/WebSocketConstants.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/websocket/WebSocketDiagnosticsCollector.java

Removed unused unqualified names from WebSocketConstants

---

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/JDTUtils.java

Resolves https://github.com/OpenLiberty/liberty-tools-intellij/issues/1075

Reduce code duplication in JDTUtils.getFieldAccessors()

---

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/beanvalidation/BeanValidationDiagnosticsCollector.java

Resolves https://github.com/OpenLiberty/liberty-tools-intellij/issues/1070

BeanValidationDiagnosticsCollector: Refactoring method and field annotation processing loops into one method.

---

src/test/resources/projects/maven/jakarta-sample/src/main/java/ng/Boolean.java
src/test/resources/projects/maven/jakarta-sample/src/main/java/ng/Byte.java
src/test/resources/projects/maven/jakarta-sample/src/main/java/ng/CharSequence.java
src/test/resources/projects/maven/jakarta-sample/src/main/java/ng/Character.java
src/test/resources/projects/maven/jakarta-sample/src/main/java/ng/Double.java
src/test/resources/projects/maven/jakarta-sample/src/main/java/ng/Float.java
src/test/resources/projects/maven/jakarta-sample/src/main/java/ng/Integer.java
src/test/resources/projects/maven/jakarta-sample/src/main/java/ng/Long.java
src/test/resources/projects/maven/jakarta-sample/src/main/java/ng/Short.java
src/test/resources/projects/maven/jakarta-sample/src/main/java/ng/String.java
src/test/resources/projects/maven/jakarta-sample/src/main/java/th/BigDecimal.java
src/test/resources/projects/maven/jakarta-sample/src/main/java/th/BigInteger.java

Resolves https://github.com/OpenLiberty/liberty-tools-intellij/issues/1080
Package mappings:
```
java.lang -> ng
java.math -> th
```
I explicitly chose these package names because they are suffixes of the Java built-in packages. Code which incorrectly matches qualified names using the `String.endsWith()` method can potentially be identified by using these imposter classes in the test application.

Create java.lang and java.math imposter classes for use in testing qualified names.

---

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/annotations/AnnotationDiagnosticsCollector.java

Resolves https://github.com/OpenLiberty/liberty-tools-intellij/issues/1068
Refactored annotation processing loops into one method as well as making some arrays into constants.

Reduce code duplication in AnnotationDiagnosticsCollector.collectDiagnostics().

---

.gitignore

Part of #911 
This change is made to prevent the inclusion of unwanted files that are created when building the plugin with IntelliJ 2024.2. It supports the necessary changes to ensure only relevant files are tracked during the build process.

Added git ignore command to remove unwanted files

---

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/cdi/ManagedBeanDiagnosticsCollector.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/cdi/ManagedBeanQuickFix.java
src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/cdi/ManagedBeanTest.java

Resolved inconsistent behaviour of @Dependency quickfix
Fixes #784

Resolved inconsistent behaviour of @Dependency quickfix

---

src/test/java/io/openliberty/tools/intellij/it/GradleSingleModMPProjectTest.java
src/test/java/io/openliberty/tools/intellij/it/GradleSingleModMPSIDProjectTest.java
src/test/java/io/openliberty/tools/intellij/it/GradleSingleModNLTRestProjectTest.java
src/test/java/io/openliberty/tools/intellij/it/MavenSingleModMPProjectTest.java
src/test/java/io/openliberty/tools/intellij/it/MavenSingleModMPSIDProjectTest.java
src/test/java/io/openliberty/tools/intellij/it/MavenSingleModNLTRestProjectTest.java
src/test/java/io/openliberty/tools/intellij/it/SingleModJakartaLSTestCommon.java
src/test/java/io/openliberty/tools/intellij/it/SingleModLibertyLSTestCommon.java
src/test/java/io/openliberty/tools/intellij/it/SingleModMPLSTestCommon.java
src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java
src/test/java/io/openliberty/tools/intellij/it/SingleModNLTRestProjectTestCommon.java

The new copyright headers specify year 2023 which is the correct year.
Fixes #1082

Refactor the automated UI tests for easier maintenance

---

src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java

Fixes #1078 #564 
As part of [Issue 564](https://github.com/OpenLiberty/liberty-tools-intellij/issues/564), container tests were previously disabled. However, recent testing has confirmed that the underlying issue no longer occurs, and these Devc tests no longer cause failures in other test cases. Therefore, this PR re-enables the container tests.

Update absoluteWLPPath in testStartInContainerActionUsingPlayToolbarButton() test

---

build.gradle
gradle.properties
src/main/resources/META-INF/plugin.xml

Fixes https://github.com/OpenLiberty/liberty-tools-intellij/issues/911
Updated intellij platform and kotlin jvm version
Updated source compatability and target compatability in build.gradle and given java version inside gradle.properties file
Changed intellij to intellijPlatform and added it inside dependencies tag
Updated runIde task in build.gradle
Added intellijPlatform tag to add buildSearchableOptions, since build, until build and add the changeNotes
updated platformVersion in gradle.properties

#911 support intellij 2024.2 by updating gradle version

---

build.gradle

Fixes #885 
I enabled the UI test task `runIdeForUiTests`, and as a result, the UI tests are currently running on IntelliJ version `2024.1.7`.

Enable Ui test task 'runIdeForUiTests'

---

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/AbstractDiagnosticsCollector.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/annotations/AnnotationDiagnosticsCollector.java

Fixes #1025 
Refactored isMatchedAnnotation() and isMatchedJavaElement() to align the changes with fully qualified names

Resolved issues with matching qualified names in AbstractDiagnosticsCollector

---

.github/workflows/build.yaml
src/test/java/io/openliberty/tools/intellij/it/SingleModJakartaLSTestCommon.java
src/test/java/io/openliberty/tools/intellij/it/SingleModLibertyLSTestCommon.java
src/test/java/io/openliberty/tools/intellij/it/SingleModMPLSTestCommon.java
src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java
src/test/java/io/openliberty/tools/intellij/it/SingleModNLTRestProjectTestCommon.java
src/test/java/io/openliberty/tools/intellij/it/TestUtils.java
src/test/resources/ci/scripts/run.sh

Fixes #1121 
When we examine the output logs of tests that experience a SocketTimeoutException we find that every subsequent test fails. Once the connection between the robot and the IDE is broken we cannot reconnect. 
The strategy is to save the JUnit output in a file and after each set of tests scan the file to see if the expected exception occurred. We use a static file reader so that it maintains its place in the file and we do not start scanning from the beginning each time. 
The benefit of detecting this exception is that we can exit the tests as soon as possible so the debugging can begin.

Detect a SocketTimeoutException and exit the JUnit tests

---

.run/liberty-tools-intellij [runIde].run.xml
DEVELOPING.md
build.gradle
gradle.properties

Fixes #1088 
By default, tasks like runIde use the IntelliJ Platform version specified in the dependencies extension. I implemented a solution by creating a new task called `runIdeLocally`, enabling us to set custom values for the Java and IntelliJ versions. This allows us to use `runIde` with the specified platform version (java 17 ) and Intellij version 2024.1.7 and `runIdeLocally` with the latest version (2024.2.2 in this case) and java 21.
Also updated the places where `runIde` is used in our code to `runIdeLocally`.

Issue #1088 - Parameterize the java target and platform target values

---

src/main/java/io/openliberty/tools/intellij/lsp4mp/MicroProfileProjectService.java

Fixes #1119 
Removed the unused method createJSONSchemaFile() as the function has dependency with the class com.intellij.json.JsonFileType, that has been deprecated since IntelliJ 2024.3 version.

Removed unused method that having a deprecated class dependency with intellij-2024.3

---

build.gradle
gradle.properties

Part of : https://github.com/OpenLiberty/liberty-tools-intellij/issues/911
The unused Java target version has been removed from gradle.properties, and the import for kotlinCompile has been added in build.gradle.

Removed unused java target version and added import for kotlinCompile

---

build.gradle

First step in delivering: https://github.com/OpenLiberty/liberty-tools-intellij/issues/1077. This PR upgrades to the final release of LSP4Jakarta 0.2.2.

Upgrade to LSP4Jakarta 0.2.2 (final release).

---

.github/workflows/build.yaml

Enabled test to the new feature branch `intellij-2024.2-support-backup`

Enable test to the new feature branch intellij-2024.2-support-backup

---

.github/workflows/build.yaml

Resolves https://github.com/OpenLiberty/liberty-tools-intellij/issues/1077
Note that an upgrade to LSP4MP 0.13.0 was also included in the initial PR https://github.com/OpenLiberty/liberty-tools-intellij/pull/1061 that was merged to the feature branch.

Integrate LSP4Jakarta 0.2.2 feature branch into main.

---

src/test/java/io/openliberty/tools/intellij/it/TestUtils.java
src/test/resources/ci/scripts/run.sh

Fixes #1122
Fix to detect the process id on Windows. I use `kill -1` and `kill -9` and `sleep 5` in an attempt to avoid the defunct process I've seen in the past.
Log showing how the Windows code works for those not familiar with Windows:
```
+ '[' 23 -eq 23 ']'
+ [[ MINGW64_NT-10.0-20348 == \M\I\N\G\W\6\4\_\N\T* ]]
+ kill -n 1 1823
+ sleep 5
./src/test/resources/ci/scripts/run.sh: line 195:  1823 Hangup                  ./gradlew runIdeForUiTests -PuseLocal=$USE_LOCAL_PLUGIN --info > remoteServer.log 2>&1
+ kill -n 9 1823
./src/test/resources/ci/scripts/run.sh: line 209: kill: (1823) - No such process
+ sleep 5
+ ps -ef
UID     PID    PPID  TTY        STIME COMMAND
runnerad    1869    1716 ?        00:08:10 /usr/bin/ps
runnerad    1716       1 ?        23:48:37 /usr/bin/bash
```
Log from …

Terminate the process running the IDE if it crashes

---

src/test/resources/ci/scripts/run.sh

Fixes #1123 
In the last pull request we terminated the running IDE after detecting the error. In this one we need to restart the IDE and restart the testing. I chose to try up to 5 times before stopping.

When the SocketTimeoutException is detected, restart testing

---

src/test/java/io/openliberty/tools/intellij/it/GradleSingleModJakartaLSTest.java
src/test/java/io/openliberty/tools/intellij/it/GradleSingleModLSTest.java
src/test/java/io/openliberty/tools/intellij/it/GradleSingleModMPLSTest.java
src/test/java/io/openliberty/tools/intellij/it/SingleModJakartaLSTestCommon.java
src/test/java/io/openliberty/tools/intellij/it/SingleModLibertyLSTestCommon.java
src/test/java/io/openliberty/tools/intellij/it/SingleModMPLSTestCommon.java
src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java
src/test/java/io/openliberty/tools/intellij/it/SingleModNLTRestProjectTestCommon.java
src/test/java/io/openliberty/tools/intellij/it/TestUtils.java
src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java
src/test/resources/ci/scripts/run.sh

Fixes #1124 
Introduce a new method to find the Welcome screen of IntelliJ. This is needed when we start IntelliJ after a crash. In this case IntelliJ will start and load the last project that was used. This is not expected by the UI robot because it always closes files and projects after each test. So the fix is to close all files and lose the current project to get back to the Welcome screen when we detect that the Welcome screen is not up. 
I also noticed that there were some unused imports so I did a sweep through all the files in the directory and updated the copyrights, removed unused imports and also extra blank lines.

Get back to the Welcome screen at start up of UI test

---

src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/AbstractDiagnosticsCollector.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/JDTUtils.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/beanvalidation/BeanValidationDiagnosticsCollector.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/beanvalidation/BeanValidationQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/cdi/ManagedBeanDiagnosticsCollector.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/cdi/ManagedBeanQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/InsertAnnotationMissingQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/RemoveAnnotationConflictQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/RemoveParamAnnotationQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/CompleteFilterAnnotationQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/CompleteServletAnnotationQuickFix.java
src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/ListenerImplementationQuickFix.java

Resolves https://github.com/OpenLiberty/liberty-tools-intellij/issues/1095

LSP4Jakarta: Reduce code duplication. Use getSimpleName() utility method for computing short names.

---

src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/annotations/ResourceAnnotationTest.java
src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/cdi/ManagedBeanTest.java
src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/di/DependencyInjectionTest.java
src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/jaxrs/ResourceMethodTest.java
src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/jsonb/JsonbDiagnosticsCollectorTest.java
src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/jsonp/JakartaJsonpTest.java
src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/servlet/JakartaServletTest.java
src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/websocket/JakartaWebSocketTest.java

Resolves https://github.com/OpenLiberty/liberty-tools-intellij/issues/1142
Also took the opportunity to clean up unused imports and to fix the indentation of code in one of the test methods.

LSP4Jakarta: Remove obsolete comments from unit tests

---

build.gradle

Fixes #1087
Disabled the native launcher warning that appears in the Windows and Linux Welcome frames. Once this fix is merged, it will prevent UI test failures caused by this warning.

Disable the native launcher warning

---

src/main/java/io/openliberty/tools/intellij/actions/ViewIntegrationTestReport.java
src/main/java/io/openliberty/tools/intellij/actions/ViewTestReport.java
src/main/java/io/openliberty/tools/intellij/actions/ViewUnitTestReport.java
src/main/resources/messages/LibertyBundles.properties

Fixes #978
The absolute path is so long you can barely understand what the good part is and what the bad part is. These file names are now relative to the project base directory so you can review them and navigate to the directory in your project to investigate.

Reformat messages concerning missing test report files

---

build.gradle
gradle.properties
src/test/java/io/openliberty/tools/intellij/it/SingleModLibertyLSTestCommon.java
src/test/java/io/openliberty/tools/intellij/it/SingleModMPLSTestCommon.java
src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java
src/test/java/io/openliberty/tools/intellij/it/SingleModNLTRestProjectTestCommon.java
src/test/java/io/openliberty/tools/intellij/it/TestUtils.java
src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java
src/test/java/io/openliberty/tools/intellij/it/fixtures/ProjectFrameFixture.java

Fixes [#1066](https://github.com/OpenLiberty/liberty-tools-intellij/issues/1066) and [#1127](https://github.com/OpenLiberty/liberty-tools-intellij/issues/1127)
UI Code Modifications for Mac:
* Updated the UI code to support IntelliJ versions 2024.3 and 2024.2.
* Introduced conditional logic to handle UI differences between these versions, ensuring compatibility with both.
* Added conditional checks to handle differences in the UI between Mac and Windows/Linux platforms.
Issue Resolutions During Integration:
* NullPointerException in detectFatalError Method:
* While integrating changes from the main and intellij-2024.2-support-backup branches into the updated UI code, encountered a NullPointerException when running individual UI tests locally.
* Root Cause: The detectFatalError method …

#1127 mac UI test integration

---

build.gradle

Fixes #1162 
Note: Do NOT merge until LTI 24.0.12 is ready for a production build.

Update to release version in repo

---

DEVELOPING.md
build.gradle

Fixes #1157 
Updated build.gradle to include a comment explaining the purpose of setting memoryMaximumSize = "2g" in JavaCompile tasks. This change addresses out-of-memory errors encountered during test compilation by setting the maximum Java heap size using the -Xmx option, ensuring sufficient heap space.
Added a note to DEVELOPING.md to guide developers on resolving potential out-of-memory errors in the future by increasing the memoryMaximumSize option in build.gradle.

Added comment in build.gradle and developing.md for heap size

---

src/test/java/io/openliberty/tools/intellij/it/SingleModLibertyLSTestCommon.java
src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java

Fixes #953
Added four more automated UI tests to verify matching completion items in the server.env and bootstrap.properties files.
Current Scenarios we have right now:
- Full capital case letters insert into server.env
- Full lowercase letters insert into bootstrap.properties
I have added 4 more scenarios. Below are the 4 scenarios, and I have added tests for them, so they are included in this PR.
1.  Full lowercase letters insert into server.env
2.  A mix of lowercase and capital case letters insert into server.env
3.  Full capital case letters insert into bootstrap.properties
4.  A mix of lowercase and capital case letters insert into bootstrap.properties

Add automated UI tests for case insensitive matching of completion items 

---

src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java

Fixes #1165
Updated the UI test to check whether the IntelliJ IDE is already in a `maximized` or `minimized` state before performing the `maximize` or `minimize` actions on the IntelliJ IDE window. 
This fix checks the size of the IntelliJ window against the screen size to decide if the window is maximized or not. If the window's width or height is greater than or equal to the screen size, it is considered full screen.
The reason for checking whether the window's width or height is greater than or equal to the screen size is that sometimes the IntelliJ window size exceeds the screen size. In such cases, it can be considered as full screen. It is not necessary for both the width and height of the IntelliJ IDE window to be greater than or equal to the screen size; if at least one dimension …

Add condition check to determine if the IntelliJ window is currently full screen

---

src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/core/BaseJakartaTest.java

Fixes #1086 
As per the alternatives suggested by [Jetbrains](https://github.com/JetBrains/intellij-community/blob/d232a78a114ab5150c25bc5726fd909cbb0b374d/platform/core-api/src/com/intellij/openapi/module/Module.java#L41-L42)

Removed the Unused createMavenModule method 

---

docs/user-guide.md

Resolves https://github.com/OpenLiberty/liberty-tools-intellij/issues/1214

Include LSP4IJ 0.9.0 in the list of versions tested with LTI 24.0.12.

---

src/test/java/io/openliberty/tools/intellij/it/SingleModLibertyLSTestCommon.java
src/test/java/io/openliberty/tools/intellij/it/fixtures/ProjectFrameFixture.java

Fixes #852 
testCompletionValuesInServerEnv Video
https://github.com/user-attachments/assets/2eeb850c-7fed-47fb-a07a-5f44a87e2ffa
testCompletionValuesInBootstrapProperties Video
https://github.com/user-attachments/assets/d00c431b-1ecb-4d53-a6a8-ab58a9b8f6ad

UI test to check for relevant completion options in bootstrap.properties and server.env

---

gradle.properties
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/ProjectLabelManager.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/PropertiesManager.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/java/diagnostics/DiagnosticsHandler.java

Fixes #1176 
The deprecated method `DumbService.runReadActionInSmartMode(Computable)` has been removed. 
Its replacement, `ReadAction.nonBlocking(...).inSmartMode(project).executeSynchronously()`, is not explicitly required here because the methods `ProjectLabelManager.getProjectLabelInfo()`, `PropertiesManager.findPropertyLocation()`, and `DiagnosticsHandler.collectDiagnostics()` are already executed within a NonBlocking ReadAction.

Replaced the usage of deprecated method DumbService.runReadActionInSmartMode(Computable)

---

src/test/resources/projects/gradle/sampleGradleMPLSApp/gradle/wrapper/gradle-wrapper.properties

In case testing times out unexpectedly one day.
Fixes #1221

Upgrade sampleGradleMPLSApp from Gradle 7.6 to 7.6.1

---

src/main/java/io/openliberty/tools/intellij/LibertyExplorer.java
src/main/java/io/openliberty/tools/intellij/LibertyModules.java
src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunConfiguration.java
src/main/java/io/openliberty/tools/intellij/util/BuildFile.java
src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java
src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java

The fix for the bug is in `LibertyRunConfiguration` but to get that new method the logic needed to be extracted from the class `LibertyExplorer`. See the comment in the issue. 
In the process of refactoring that method (`buildTree()`) I noticed that two loops did almost the same things for Gradle and Maven files so I combined them into one loop. A lot of code was removed. Also the module code that moved from `LibertyExplorer` to `LibertyModules` was two loops and they were combined into one. I added data validation to the class `BuildFile` mainly to document the acceptable values but also to ensure correctness.
I noticed that some error statements in the test log did not indicate that the test was going to retry and this confused me so I took the opportunity to change the output string by …

Search for Liberty modules to use in Run/Debug config

---

src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java

Fixes #1238
Add a try/catch block to handle the case where there is no terminal to be found. Just give up and return.

Handle situation when there is no terminal tab to close

---

src/main/java/io/openliberty/tools/intellij/LibertyExplorer.java
src/main/java/io/openliberty/tools/intellij/LibertyModule.java
src/main/java/io/openliberty/tools/intellij/LibertyModuleNode.java
src/main/java/io/openliberty/tools/intellij/LibertyModules.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyDevStartAction.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyDevStartContainerAction.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyGeneralAction.java
src/main/java/io/openliberty/tools/intellij/actions/LibertyProjectAction.java
src/main/java/io/openliberty/tools/intellij/actions/ViewGradleConfig.java
src/main/java/io/openliberty/tools/intellij/actions/ViewIntegrationTestReport.java
src/main/java/io/openliberty/tools/intellij/actions/ViewPomXml.java
src/main/java/io/openliberty/tools/intellij/actions/ViewTestReport.java
src/main/java/io/openliberty/tools/intellij/actions/ViewUnitTestReport.java
src/main/java/io/openliberty/tools/intellij/util/BuildFile.java
src/main/java/io/openliberty/tools/intellij/util/Constants.java
src/main/java/io/openliberty/tools/intellij/util/DebugModeHandler.java
src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java
src/main/java/io/openliberty/tools/intellij/util/TreeDataProvider.java

Fixes #1234 
Three code improvements were suggested in the review of issue #1202.
1. Return `this` instead of calling `getInstance()`
2. Synchronize access to `libertyModules` in `addLibertyModule()`
3. Use an enum instead of Strings for project type in the area of Liberty actions. Using an enum allows us to remove some string checking code that is no longer required. This affects a lot of files but it makes the code more robust.

Extra rework for issue 1202

---

.github/workflows/pr-slack-notification.yaml

Fixes #1244 
Removed  use of Special character # from the PR number for the slack message
With the latest changes in this PR there is no issue with the text from GitHub (title of the PR), and it include '#' or '@' characters without any problems.

Removed  use of # from the PR number

---

.github/workflows/build.yaml
build.gradle

In the current 24.0.12 tag, the condition for retrieving the local LSP4IJ is not working as expected. 
As a result, it defaults to version 0.8.1 specified in the `build.gradle` file. 
To address this, we have created a branch based on 24.0.12 with the necessary changes to correctly retrieve the local LSP4IJ path. This allows the cron job tag to be updated from `24.0.12` to `24.0.12-lsp4ijFix`, ensuring that the correct condition is applied and the local LSP4IJ is used as intended, enabling the cron job to run as expected.

LTI 24.0.12: Retrieve the local Lsp4ij Path correctly

---

src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunConfiguration.java

The parent class already has a method to suggest a name. The new config mechanism calls this method when creating a config and also when cloning the config to detect changes while you type.
Fixes #180 
This code suggests artifact id for Maven and directory name for Gradle.

Override the method suggestedName() used during config creation

---

src/main/java/io/openliberty/tools/intellij/actions/LibertyGeneralAction.java

Resolves https://github.com/OpenLiberty/liberty-tools-intellij/issues/1260
Moved common logic into a shared method. Pass in a mapping function to obtain the `String[]` from the `List`.

LibertyGeneralAction: Refactor to*() methods to use a mapping function.

---

.github/workflows/build.yaml
src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java

Change the importProject using UI to utilize the IntelliJ API instead

---

src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/core/java/ChangeUtil.java
src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/core/java/TextEditConverter.java

Fixes #1187 
The method convertToTextDocumentEdit(int) has 0 usages in our code . Hence removed the method and made the necessary refactoring

Address usage of deprecated constructor 'VersionedTextDocumentIdentifier'

---

src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/jaxrs/java/JaxRsWorkspaceSymbolParticipant.java

Fixes #1185 
As per Replacement [Doc](https://github.com/openjdk/jdk/blob/ceae2b977dac58a9b2c09e42cb256c94eff9222b/src/java.base/share/classes/java/net/URL.java#L404-L408)

Deprecated constructor 'URL.<init>(String)' changed to URI.toURL

---

build.gradle
gradle.properties

This pull request introduces a new way to specify the version number of language server dependencies. They are needed in two locations so it makes sense to specify the number once in the `gradle.properties` (like some others are) and then to reference that value.
We also update lsp4jakarta from 0.2.2 to 0.2.3.
Fixes #1309

Update the Lsp4Jakarta version number to the latest

---

src/test/java/io/openliberty/tools/intellij/it/SingleModJakartaLSTestCommon.java

Fixes #1307
Our current test checks for hover data only once and immediately validates the expected data. However, in Windows builds, the initially detected `HoverData` was sometimes incorrect, leading to test failures. This issue might be due to machine slowness, causing a delay in hover data reflection. To address this, the test now checks up to `five` times for the expected data. In some cases, three checks were sufficient, so I set the loop iteration value to five for reliability.
This is how the build logs appear when our expected hover data is not found on the first attempt.

Add fix for rechecking the expected hover data

---

src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java

Part of  fix #1204
Since the corresponding tests are failing only on Windows OS, I added a delay between character entries for Windows only. I increased the iteration count from 10 to 15 to provide more delay, reduced the sleep time from 20 to 10 to avoid unnecessary delays between iterations in diagnostic test method, and increased the sleep time for the QuickFix hover data method.
I have set a delay of `200` after multiple checks because if we set it to 500 or above, we may get a timeout exception, and if we set it to 300, we may get a 'List is empty' exception, both of which cause test failures.
So, I chose the value 200. The default value is 50, which works faster on Windows OS, but on other operating systems, it enters at a normal speed. That's why I added a condition.

Increase Delay to Obtain the Diagnostic, Leading to Test Pass

---

build.gradle
gradle.properties
src/test/java/io/openliberty/tools/intellij/it/SingleModJakartaLSTestCommon.java
src/test/java/io/openliberty/tools/intellij/it/SingleModLibertyLSTestCommon.java
src/test/java/io/openliberty/tools/intellij/it/SingleModMPLSTestCommon.java
src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java
src/test/java/io/openliberty/tools/intellij/it/fixtures/ProjectFrameFixture.java

Fixes #1297 - updated to latest Intellij version 251.23774.16 and IntelliJ Platform Gradle Plugin to version 2.3.0
Fixes #1298 - Added a condition to check if the version is 2025.1—if so, it uses the `MyProjectViewTree` class; otherwise, it defaults to the `ProjectViewTree` class.
Fixes #1299 - With the beta build this issue is resolved.
Fixes #1302 - Modified the runJs script in the importProject function to accommodate to open both directory as well as project

Changed into IntelliJ 2025.1 version

---

src/test/java/io/openliberty/tools/intellij/it/GradleSingleModMPCfgProjectTest.java
src/test/java/io/openliberty/tools/intellij/it/GradleSingleModMPSIDProjectTest.java
src/test/java/io/openliberty/tools/intellij/it/MavenSingleModMPCfgProjectTest.java
src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectCfgTestCommon.java
src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java

In order to trigger the bug the Liberty project must not have been loaded by a previous test case. Also the Liberty dashboard must not have been opened since IntelliJ started up. The state of the project will even be persisted if you close the workspace and go back to the Welcome screen and open a different project or the same project. 
So this test case copies an existing project into a new location so that the project will be treated as unique. This is similar to the `GradleSingleModMPSIDProjectTest` project which makes a copy.  This test case also does not open the Liberty dashboard like all the other UI test cases do. Finally there is just one test in this environment. I tested that it fails for 24.0.12 but it passes with the fix for #1202.
I updated some comments in …

Create a new test case for Run/Debug Configurations

---

build.gradle
docs/user-guide.md

Updated LSP4IJ version to 0.14.0
Updated change notes as the LTI 25.0.5 has been tested with LSP4IJ 0.14.0

Updated LSP4IJ version to 0.14.0

---

src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java

Fixes #1392 
Checked the TerminalEngine enum contains CLASSIC, as it is not available for old intellij versions

Resolved terminal exception for liberty:start action for lower intellij versions
